2021-04-22 13:47:38,460 INFO 2824 6848 ocr.py main():24 Program started
2021-04-22 13:47:38,487 DEBUG 2824 6848 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:47:38,487 DEBUG 2824 6848 ocr.py main():41 checking params, error code: 0
2021-04-22 13:47:38,488 DEBUG 2824 6848 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:47:38,488 DEBUG 2824 6848 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:47:38,488 DEBUG 2824 6848 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:47:38,488 INFO 2824 6848 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:47:38,489 INFO 2824 6848 reader.py validate_source():73 scanning files...
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:47:39,257 INFO 2824 6848 reader.py output():169 checking output
2021-04-22 13:47:39,262 DEBUG 2824 6848 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:47:39,262 INFO 2824 6848 reader.py merge_output():212 merging scanned output
2021-04-22 13:48:07,610 INFO 5532 3380 ocr.py main():24 Program started
2021-04-22 13:48:07,640 DEBUG 5532 3380 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:48:07,640 DEBUG 5532 3380 ocr.py main():41 checking params, error code: 0
2021-04-22 13:48:07,640 DEBUG 5532 3380 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:48:07,640 DEBUG 5532 3380 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:48:07,640 DEBUG 5532 3380 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:48:07,640 INFO 5532 3380 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:48:07,642 INFO 5532 3380 reader.py validate_source():73 scanning files...
2021-04-22 13:48:07,653 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:48:08,419 INFO 5532 3380 reader.py output():169 checking output
2021-04-22 13:48:08,419 DEBUG 5532 3380 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:48:08,420 INFO 5532 3380 reader.py merge_output():212 merging scanned output
2021-04-22 13:51:55,428 INFO 7036 1560 ocr.py main():24 Program started
2021-04-22 13:51:55,454 DEBUG 7036 1560 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:51:55,454 DEBUG 7036 1560 ocr.py main():41 checking params, error code: 0
2021-04-22 13:51:55,455 DEBUG 7036 1560 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:51:55,455 DEBUG 7036 1560 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:51:55,455 DEBUG 7036 1560 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:51:55,455 INFO 7036 1560 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:51:55,456 INFO 7036 1560 reader.py validate_source():73 scanning files...
2021-04-22 13:51:55,467 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:51:55,467 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:51:55,467 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:51:55,468 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:51:55,468 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:51:56,211 INFO 7036 1560 reader.py output():169 checking output
2021-04-22 13:51:56,222 DEBUG 7036 1560 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:51:56,222 DEBUG 7036 1560 reader.py output():183 FILE: dest [DND] basename and dest different. dest_file: DND/barbaro.txt
2021-04-22 13:51:56,222 INFO 7036 1560 reader.py merge_output():213 merging scanned output
2021-04-22 13:53:38,363 INFO 7000 5976 ocr.py main():24 Program started
2021-04-22 13:53:38,370 DEBUG 7000 5976 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:53:38,370 DEBUG 7000 5976 ocr.py main():41 checking params, error code: 0
2021-04-22 13:53:38,371 DEBUG 7000 5976 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:53:38,371 DEBUG 7000 5976 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:53:38,371 DEBUG 7000 5976 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:53:38,371 INFO 7000 5976 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:53:38,372 INFO 7000 5976 reader.py validate_source():73 scanning files...
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:53:39,288 INFO 7000 5976 reader.py output():169 checking output
2021-04-22 13:53:39,293 DEBUG 7000 5976 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:53:39,293 INFO 7000 5976 reader.py create_dir():229 Created directory DND
2021-04-22 13:53:39,310 DEBUG 7000 5976 reader.py validate_dest():246 path dest file: DND/barbaro.txt\scan.txt
2021-04-22 13:53:39,311 DEBUG 7000 5976 reader.py output():191 DIR: dest [DND] exists. dest_file: DND/barbaro.txt\scan.txt
2021-04-22 13:53:39,311 INFO 7000 5976 reader.py merge_output():213 merging scanned output
2021-04-22 13:53:39,311 ERROR 7000 5976 reader.py output():203 Error file not found on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 199, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'DND\\barbaro.txt\\scan.txt'
2021-04-22 14:01:13,819 INFO 3980 4764 ocr.py main():24 Program started
2021-04-22 14:01:13,843 DEBUG 3980 4764 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:01:13,843 DEBUG 3980 4764 ocr.py main():41 checking params, error code: 0
2021-04-22 14:01:13,843 DEBUG 3980 4764 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:01:13,844 DEBUG 3980 4764 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:01:13,844 DEBUG 3980 4764 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:01:13,844 INFO 3980 4764 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:01:13,845 INFO 3980 4764 reader.py validate_source():73 scanning files...
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:01:14,616 INFO 3980 4764 reader.py output():169 checking output
2021-04-22 14:01:14,630 DEBUG 3980 4764 reader.py output():180 dirname: DND/classi, path to check = dir
2021-04-22 14:01:14,630 INFO 3980 4764 reader.py create_dir():232 Created directory DND\classi
2021-04-22 14:01:14,647 DEBUG 3980 4764 reader.py validate_dest():249 path dest file: DND/classi/barbaro.txt\scan.txt
2021-04-22 14:01:14,648 DEBUG 3980 4764 reader.py output():194 DIR: dest [DND/classi] exists. dest_file: DND/classi/barbaro.txt\scan.txt
2021-04-22 14:01:14,648 INFO 3980 4764 reader.py merge_output():216 merging scanned output
2021-04-22 14:01:14,680 ERROR 3980 4764 reader.py output():206 Error file not found on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 202, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'DND\\classi\\barbaro.txt\\scan.txt'
2021-04-22 14:01:26,726 INFO 7112 6420 ocr.py main():24 Program started
2021-04-22 14:01:26,747 DEBUG 7112 6420 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:01:26,747 DEBUG 7112 6420 ocr.py main():41 checking params, error code: 0
2021-04-22 14:01:26,747 DEBUG 7112 6420 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:01:26,747 DEBUG 7112 6420 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:01:26,747 DEBUG 7112 6420 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:01:26,748 INFO 7112 6420 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:01:26,748 INFO 7112 6420 reader.py validate_source():73 scanning files...
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:01:27,522 INFO 7112 6420 reader.py output():169 checking output
2021-04-22 14:01:27,532 DEBUG 7112 6420 reader.py output():180 dirname: DND/classi, path to check = dir
2021-04-22 14:01:27,533 DEBUG 7112 6420 reader.py output():186 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:01:27,562 INFO 7112 6420 reader.py merge_output():216 merging scanned output
2021-04-22 14:01:27,563 ERROR 7112 6420 reader.py output():204 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 202, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 14:01:56,163 INFO 7096 5524 ocr.py main():24 Program started
2021-04-22 14:01:56,199 DEBUG 7096 5524 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:01:56,199 DEBUG 7096 5524 ocr.py main():41 checking params, error code: 0
2021-04-22 14:01:56,200 DEBUG 7096 5524 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:01:56,200 DEBUG 7096 5524 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:01:56,200 DEBUG 7096 5524 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:01:56,200 INFO 7096 5524 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:01:56,201 INFO 7096 5524 reader.py validate_source():73 scanning files...
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:01:57,024 INFO 7096 5524 reader.py output():169 checking output
2021-04-22 14:01:57,031 DEBUG 7096 5524 reader.py output():181 dirname: DND/classi, path to check = dir
2021-04-22 14:01:57,031 DEBUG 7096 5524 reader.py output():187 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:01:57,032 INFO 7096 5524 reader.py merge_output():217 merging scanned output
2021-04-22 14:01:57,032 ERROR 7096 5524 reader.py output():205 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 203, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 14:02:24,914 INFO 6444 6728 ocr.py main():24 Program started
2021-04-22 14:02:24,935 DEBUG 6444 6728 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:02:24,935 DEBUG 6444 6728 ocr.py main():41 checking params, error code: 0
2021-04-22 14:02:24,935 DEBUG 6444 6728 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:02:24,935 DEBUG 6444 6728 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:02:24,935 DEBUG 6444 6728 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:02:24,935 INFO 6444 6728 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:02:24,936 INFO 6444 6728 reader.py validate_source():73 scanning files...
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:02:25,694 INFO 6444 6728 reader.py output():169 checking output
2021-04-22 14:02:25,700 DEBUG 6444 6728 reader.py output():181 dirname: DND, path to check = dir
2021-04-22 14:02:25,700 DEBUG 6444 6728 reader.py output():187 FILE: dest [DND] basename and dest different. dest_file: DND/barbaro.txt
2021-04-22 14:02:25,716 INFO 6444 6728 reader.py merge_output():217 merging scanned output
2021-04-22 14:26:54,548 INFO 1676 4292 ocr.py main():24 Program started
2021-04-22 14:26:54,563 DEBUG 1676 4292 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:26:54,563 DEBUG 1676 4292 ocr.py main():41 checking params, error code: 0
2021-04-22 14:26:54,563 DEBUG 1676 4292 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:26:54,563 DEBUG 1676 4292 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:26:54,564 DEBUG 1676 4292 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:26:54,564 INFO 1676 4292 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:26:54,581 INFO 1676 4292 reader.py validate_source():73 scanning files...
2021-04-22 14:26:54,593 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:26:55,346 INFO 1676 4292 reader.py output():169 checking output
2021-04-22 14:26:55,361 DEBUG 1676 4292 reader.py output():181 dirname: DND, path to check = dir
2021-04-22 14:26:55,361 DEBUG 1676 4292 reader.py output():187 FILE: dest [DND] basename and dest different. dest_file: DND/barbaro.txt
2021-04-22 14:26:55,375 INFO 1676 4292 reader.py merge_output():217 merging scanned output
2021-04-22 14:28:39,895 INFO 4728 2128 ocr.py main():24 Program started
2021-04-22 14:28:39,919 DEBUG 4728 2128 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:28:39,919 DEBUG 4728 2128 ocr.py main():41 checking params, error code: 0
2021-04-22 14:28:39,919 DEBUG 4728 2128 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:28:39,920 DEBUG 4728 2128 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:28:39,920 DEBUG 4728 2128 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:28:39,920 INFO 4728 2128 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:28:39,921 INFO 4728 2128 reader.py validate_source():73 scanning files...
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:28:40,688 INFO 4728 2128 reader.py output():169 checking output
2021-04-22 14:28:40,695 DEBUG 4728 2128 reader.py output():181 dirname: DND/classi, path to check = dir
2021-04-22 14:28:40,695 DEBUG 4728 2128 reader.py output():187 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/barbaro.txt
2021-04-22 14:28:40,696 INFO 4728 2128 reader.py merge_output():217 merging scanned output
2021-04-22 14:29:27,407 INFO 5816 2256 ocr.py main():24 Program started
2021-04-22 14:29:27,430 DEBUG 5816 2256 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:29:27,430 DEBUG 5816 2256 ocr.py main():41 checking params, error code: 0
2021-04-22 14:29:27,430 DEBUG 5816 2256 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:29:27,431 DEBUG 5816 2256 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:29:27,431 DEBUG 5816 2256 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:29:27,431 INFO 5816 2256 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:29:27,431 INFO 5816 2256 reader.py validate_source():73 scanning files...
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:29:28,203 INFO 5816 2256 reader.py output():169 checking output
2021-04-22 14:29:28,204 DEBUG 5816 2256 reader.py output():181 dirname: DND/classi, path to check = dir
2021-04-22 14:29:28,205 DEBUG 5816 2256 reader.py output():187 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:29:28,219 INFO 5816 2256 reader.py merge_output():217 merging scanned output
2021-04-22 14:29:28,220 ERROR 5816 2256 reader.py output():205 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 203, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 14:36:26,001 INFO 908 6332 ocr.py main():24 Program started
2021-04-22 14:36:26,023 DEBUG 908 6332 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:36:26,023 DEBUG 908 6332 ocr.py main():41 checking params, error code: 0
2021-04-22 14:36:26,023 DEBUG 908 6332 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:36:26,024 DEBUG 908 6332 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:36:26,024 DEBUG 908 6332 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:36:26,024 INFO 908 6332 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:36:26,025 INFO 908 6332 reader.py validate_source():73 scanning files...
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:36:26,783 INFO 908 6332 reader.py output():169 checking output
2021-04-22 14:36:26,812 DEBUG 908 6332 reader.py output():182 dirname: DND/classi, path to check = dir
2021-04-22 14:36:26,812 DEBUG 908 6332 reader.py output():188 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/barbaro.txt
2021-04-22 14:36:26,827 INFO 908 6332 reader.py merge_output():218 merging scanned output
2021-04-22 14:36:55,309 INFO 4292 6796 ocr.py main():24 Program started
2021-04-22 14:36:55,326 DEBUG 4292 6796 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:36:55,326 DEBUG 4292 6796 ocr.py main():41 checking params, error code: 0
2021-04-22 14:36:55,326 DEBUG 4292 6796 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:36:55,327 DEBUG 4292 6796 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:36:55,327 DEBUG 4292 6796 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:36:55,327 INFO 4292 6796 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:36:55,328 INFO 4292 6796 reader.py validate_source():73 scanning files...
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:36:56,102 INFO 4292 6796 reader.py output():169 checking output
2021-04-22 14:36:56,104 DEBUG 4292 6796 reader.py output():182 dirname: DND/classi, path to check = dir
2021-04-22 14:36:56,104 DEBUG 4292 6796 reader.py output():188 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:36:56,104 INFO 4292 6796 reader.py merge_output():218 merging scanned output
2021-04-22 14:36:56,105 ERROR 4292 6796 reader.py output():206 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 204, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 15:04:23,039 INFO 5904 5836 ocr.py main():24 Program started
2021-04-22 15:04:23,046 DEBUG 5904 5836 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/scan.txt, lang=eng, prefix=scan, stats=False
2021-04-22 15:04:23,046 DEBUG 5904 5836 ocr.py main():41 checking params, error code: 0
2021-04-22 15:04:23,046 DEBUG 5904 5836 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:04:23,047 DEBUG 5904 5836 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:04:23,047 DEBUG 5904 5836 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:04:23,047 INFO 5904 5836 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:04:23,063 INFO 5904 5836 reader.py validate_source():73 scanning files...
2021-04-22 15:04:23,108 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:04:23,109 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:04:23,109 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:04:23,109 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:04:23,110 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:04:23,857 INFO 5904 5836 reader.py output():169 checking output
2021-04-22 15:04:23,876 DEBUG 5904 5836 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:04:23,876 DEBUG 5904 5836 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/scan.txt
2021-04-22 15:04:23,876 INFO 5904 5836 reader.py merge_output():219 merging scanned output
2021-04-22 15:05:42,916 INFO 5620 4968 ocr.py main():24 Program started
2021-04-22 15:05:42,944 DEBUG 5620 4968 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/scan.txt, lang=eng, prefix=scan, stats=False
2021-04-22 15:05:42,944 DEBUG 5620 4968 ocr.py main():41 checking params, error code: 0
2021-04-22 15:05:42,944 DEBUG 5620 4968 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:05:42,944 DEBUG 5620 4968 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:05:42,946 DEBUG 5620 4968 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:05:42,946 INFO 5620 4968 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:05:42,946 INFO 5620 4968 reader.py validate_source():73 scanning files...
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:05:43,711 INFO 5620 4968 reader.py output():169 checking output
2021-04-22 15:05:43,728 DEBUG 5620 4968 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:05:43,728 DEBUG 5620 4968 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/scan.txt
2021-04-22 15:05:43,728 INFO 5620 4968 reader.py merge_output():219 merging scanned output
2021-04-22 15:06:50,648 INFO 6696 5396 ocr.py main():24 Program started
2021-04-22 15:06:50,669 DEBUG 6696 5396 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/, lang=eng, prefix=scan, stats=False
2021-04-22 15:06:50,670 DEBUG 6696 5396 ocr.py main():41 checking params, error code: 0
2021-04-22 15:06:50,670 DEBUG 6696 5396 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:06:50,670 DEBUG 6696 5396 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:06:50,671 DEBUG 6696 5396 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:06:50,671 INFO 6696 5396 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:06:50,671 INFO 6696 5396 reader.py validate_source():73 scanning files...
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:06:51,429 INFO 6696 5396 reader.py output():169 checking output
2021-04-22 15:06:51,456 DEBUG 6696 5396 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:06:51,456 DEBUG 6696 5396 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/
2021-04-22 15:06:51,456 INFO 6696 5396 reader.py merge_output():219 merging scanned output
2021-04-22 15:06:51,457 ERROR 6696 5396 reader.py output():207 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'scans'
2021-04-22 15:10:55,133 INFO 2088 3796 ocr.py main():24 Program started
2021-04-22 15:10:55,161 DEBUG 2088 3796 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans, lang=eng, prefix=scan, stats=False
2021-04-22 15:10:55,161 DEBUG 2088 3796 ocr.py main():41 checking params, error code: 0
2021-04-22 15:10:55,161 DEBUG 2088 3796 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:10:55,161 DEBUG 2088 3796 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:10:55,161 DEBUG 2088 3796 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:10:55,161 INFO 2088 3796 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:10:55,161 INFO 2088 3796 reader.py validate_source():73 scanning files...
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:10:55,176 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:10:56,024 INFO 2088 3796 reader.py output():169 checking output
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py validate_dest():252 path dest file: scans\scan.txt
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py validate_dest():256 dir content: ['scan.txt']
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py validate_dest():266 dest file: scans\scan_1.txt
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py output():191 DIR: dest [scans] exists. dest_file: scans\scan_1.txt
2021-04-22 15:10:56,047 INFO 2088 3796 reader.py merge_output():219 merging scanned output
2021-04-22 15:12:48,341 INFO 6296 4304 ocr.py main():24 Program started
2021-04-22 15:12:48,359 DEBUG 6296 4304 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane, lang=eng, prefix=scan, stats=False
2021-04-22 15:12:48,359 DEBUG 6296 4304 ocr.py main():41 checking params, error code: 0
2021-04-22 15:12:48,359 DEBUG 6296 4304 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:12:48,359 DEBUG 6296 4304 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:12:48,359 DEBUG 6296 4304 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:12:48,359 INFO 6296 4304 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:12:48,360 INFO 6296 4304 reader.py validate_source():73 scanning files...
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:12:49,133 INFO 6296 4304 reader.py output():169 checking output
2021-04-22 15:12:49,160 DEBUG 6296 4304 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:12:49,160 DEBUG 6296 4304 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/cane
2021-04-22 15:12:49,160 INFO 6296 4304 reader.py merge_output():219 merging scanned output
2021-04-22 15:12:53,117 INFO 6008 1560 ocr.py main():24 Program started
2021-04-22 15:12:53,139 DEBUG 6008 1560 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane/, lang=eng, prefix=scan, stats=False
2021-04-22 15:12:53,139 DEBUG 6008 1560 ocr.py main():41 checking params, error code: 0
2021-04-22 15:12:53,139 DEBUG 6008 1560 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:12:53,140 DEBUG 6008 1560 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:12:53,140 DEBUG 6008 1560 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:12:53,140 INFO 6008 1560 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:12:53,141 INFO 6008 1560 reader.py validate_source():73 scanning files...
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:12:53,914 INFO 6008 1560 reader.py output():169 checking output
2021-04-22 15:12:53,934 DEBUG 6008 1560 reader.py output():182 dirname: scans/cane, path to check = dir
2021-04-22 15:12:53,935 DEBUG 6008 1560 reader.py output():201 FILE: dest [scans/cane] exists. dest_file: scans/cane/
2021-04-22 15:12:53,935 INFO 6008 1560 reader.py merge_output():219 merging scanned output
2021-04-22 15:13:18,327 INFO 5232 2792 ocr.py main():24 Program started
2021-04-22 15:13:18,355 DEBUG 5232 2792 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane, lang=eng, prefix=scan, stats=False
2021-04-22 15:13:18,355 DEBUG 5232 2792 ocr.py main():41 checking params, error code: 0
2021-04-22 15:13:18,355 DEBUG 5232 2792 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:13:18,356 DEBUG 5232 2792 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:13:18,356 DEBUG 5232 2792 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:13:18,356 INFO 5232 2792 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:13:18,357 INFO 5232 2792 reader.py validate_source():73 scanning files...
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:13:19,117 INFO 5232 2792 reader.py output():169 checking output
2021-04-22 15:13:19,142 DEBUG 5232 2792 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:13:19,142 DEBUG 5232 2792 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/cane
2021-04-22 15:13:19,143 INFO 5232 2792 reader.py merge_output():219 merging scanned output
2021-04-22 15:13:30,898 INFO 1868 2628 ocr.py main():24 Program started
2021-04-22 15:13:30,923 DEBUG 1868 2628 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane, lang=eng, prefix=scan, stats=False
2021-04-22 15:13:30,923 DEBUG 1868 2628 ocr.py main():41 checking params, error code: 0
2021-04-22 15:13:30,923 DEBUG 1868 2628 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:13:30,923 DEBUG 1868 2628 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:13:30,924 DEBUG 1868 2628 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:13:30,924 INFO 1868 2628 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:13:30,924 INFO 1868 2628 reader.py validate_source():73 scanning files...
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:13:31,711 INFO 1868 2628 reader.py output():169 checking output
2021-04-22 15:13:31,739 DEBUG 1868 2628 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:13:31,739 DEBUG 1868 2628 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/cane
2021-04-22 15:13:31,739 INFO 1868 2628 reader.py merge_output():219 merging scanned output
2021-04-22 15:36:54,656 INFO 5508 3412 ocr.py main():24 Program started
2021-04-22 15:36:54,676 DEBUG 5508 3412 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd, lang=eng, prefix=scan, stats=False
2021-04-22 15:36:54,676 DEBUG 5508 3412 ocr.py main():41 checking params, error code: 0
2021-04-22 15:36:54,676 DEBUG 5508 3412 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:36:54,676 DEBUG 5508 3412 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:36:54,677 DEBUG 5508 3412 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:36:54,677 INFO 5508 3412 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:36:54,677 INFO 5508 3412 reader.py validate_source():73 scanning files...
2021-04-22 15:36:54,690 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:36:55,455 INFO 5508 3412 reader.py output():169 checking output
2021-04-22 15:36:55,472 DEBUG 5508 3412 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:36:55,473 INFO 5508 3412 reader.py create_dir():235 Created directory dnd
2021-04-22 15:36:55,474 DEBUG 5508 3412 reader.py output():196 DIR: dest [dnd] exists. dest_file: dnd
2021-04-22 15:36:55,474 INFO 5508 3412 reader.py merge_output():219 merging scanned output
2021-04-22 15:36:55,475 ERROR 5508 3412 reader.py output():207 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'dnd'
2021-04-22 15:37:14,141 INFO 5148 6888 ocr.py main():24 Program started
2021-04-22 15:37:14,170 DEBUG 5148 6888 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 15:37:14,170 DEBUG 5148 6888 ocr.py main():41 checking params, error code: 0
2021-04-22 15:37:14,170 DEBUG 5148 6888 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:37:14,170 DEBUG 5148 6888 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:37:14,170 DEBUG 5148 6888 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:37:14,171 INFO 5148 6888 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:37:14,171 INFO 5148 6888 reader.py validate_source():73 scanning files...
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:37:14,937 INFO 5148 6888 reader.py output():169 checking output
2021-04-22 15:37:14,959 DEBUG 5148 6888 reader.py output():182 dirname: dnd, path to check = dir
2021-04-22 15:37:14,959 INFO 5148 6888 reader.py create_dir():235 Created directory dnd
2021-04-22 15:37:14,960 DEBUG 5148 6888 reader.py output():196 DIR: dest [dnd] exists. dest_file: dnd/barbaro.txt
2021-04-22 15:37:14,960 INFO 5148 6888 reader.py merge_output():219 merging scanned output
2021-04-22 15:37:24,438 INFO 5800 4748 ocr.py main():24 Program started
2021-04-22 15:37:24,444 DEBUG 5800 4748 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd, lang=eng, prefix=scan, stats=False
2021-04-22 15:37:24,444 DEBUG 5800 4748 ocr.py main():41 checking params, error code: 0
2021-04-22 15:37:24,444 DEBUG 5800 4748 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:37:24,444 DEBUG 5800 4748 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:37:24,444 DEBUG 5800 4748 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:37:24,444 INFO 5800 4748 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:37:24,459 INFO 5800 4748 reader.py validate_source():73 scanning files...
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:37:25,220 INFO 5800 4748 reader.py output():169 checking output
2021-04-22 15:37:25,245 DEBUG 5800 4748 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:37:25,246 DEBUG 5800 4748 reader.py validate_dest():252 path dest file: dnd\scan.txt
2021-04-22 15:37:25,246 DEBUG 5800 4748 reader.py output():191 DIR: dest [dnd] exists. dest_file: dnd\scan.txt
2021-04-22 15:37:25,248 INFO 5800 4748 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:08,828 INFO 4332 6948 ocr.py main():24 Program started
2021-04-22 15:39:08,856 DEBUG 4332 6948 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi/baba.tzt, lang=eng, prefix=scan, stats=False
2021-04-22 15:39:08,857 DEBUG 4332 6948 ocr.py main():41 checking params, error code: 0
2021-04-22 15:39:08,857 DEBUG 4332 6948 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:39:08,857 DEBUG 4332 6948 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:39:08,857 DEBUG 4332 6948 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:39:08,858 INFO 4332 6948 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:39:08,860 INFO 4332 6948 reader.py validate_source():73 scanning files...
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:39:09,611 INFO 4332 6948 reader.py output():169 checking output
2021-04-22 15:39:09,634 DEBUG 4332 6948 reader.py output():182 dirname: dnd/classi, path to check = dir
2021-04-22 15:39:09,634 INFO 4332 6948 reader.py create_dir():235 Created directory dnd\classi
2021-04-22 15:39:09,635 DEBUG 4332 6948 reader.py output():196 DIR: dest [dnd/classi] exists. dest_file: dnd/classi/baba.tzt
2021-04-22 15:39:09,636 INFO 4332 6948 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:41,012 INFO 6828 3980 ocr.py main():24 Program started
2021-04-22 15:39:41,042 DEBUG 6828 3980 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=baba.tzt, lang=eng, prefix=scan, stats=False
2021-04-22 15:39:41,043 DEBUG 6828 3980 ocr.py main():41 checking params, error code: 0
2021-04-22 15:39:41,043 DEBUG 6828 3980 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:39:41,043 DEBUG 6828 3980 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:39:41,043 DEBUG 6828 3980 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:39:41,044 INFO 6828 3980 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:39:41,044 INFO 6828 3980 reader.py validate_source():73 scanning files...
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:39:41,814 INFO 6828 3980 reader.py output():169 checking output
2021-04-22 15:39:41,834 DEBUG 6828 3980 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:39:41,834 DEBUG 6828 3980 reader.py output():201 FILE: dest [baba.tzt] exists. dest_file: baba.tzt
2021-04-22 15:39:41,834 INFO 6828 3980 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:46,454 INFO 6952 4884 ocr.py main():24 Program started
2021-04-22 15:39:46,480 DEBUG 6952 4884 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=baba/, lang=eng, prefix=scan, stats=False
2021-04-22 15:39:46,480 DEBUG 6952 4884 ocr.py main():41 checking params, error code: 0
2021-04-22 15:39:46,480 DEBUG 6952 4884 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:39:46,480 DEBUG 6952 4884 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:39:46,480 DEBUG 6952 4884 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:39:46,480 INFO 6952 4884 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:39:46,481 INFO 6952 4884 reader.py validate_source():73 scanning files...
2021-04-22 15:39:46,493 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:39:46,493 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:39:46,494 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:39:46,494 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:39:46,494 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:39:47,235 INFO 6952 4884 reader.py output():169 checking output
2021-04-22 15:39:47,260 DEBUG 6952 4884 reader.py output():182 dirname: baba, path to check = dir
2021-04-22 15:39:47,260 INFO 6952 4884 reader.py create_dir():235 Created directory baba
2021-04-22 15:39:47,260 DEBUG 6952 4884 reader.py output():196 DIR: dest [baba] exists. dest_file: baba/
2021-04-22 15:39:47,261 INFO 6952 4884 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:47,261 ERROR 6952 4884 reader.py output():207 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'baba'
