2021-04-22 13:47:38,460 INFO 2824 6848 ocr.py main():24 Program started
2021-04-22 13:47:38,487 DEBUG 2824 6848 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:47:38,487 DEBUG 2824 6848 ocr.py main():41 checking params, error code: 0
2021-04-22 13:47:38,488 DEBUG 2824 6848 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:47:38,488 DEBUG 2824 6848 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:47:38,488 DEBUG 2824 6848 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:47:38,488 INFO 2824 6848 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:47:38,489 INFO 2824 6848 reader.py validate_source():73 scanning files...
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:47:38,501 DEBUG 2824 6848 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:47:39,257 INFO 2824 6848 reader.py output():169 checking output
2021-04-22 13:47:39,262 DEBUG 2824 6848 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:47:39,262 INFO 2824 6848 reader.py merge_output():212 merging scanned output
2021-04-22 13:48:07,610 INFO 5532 3380 ocr.py main():24 Program started
2021-04-22 13:48:07,640 DEBUG 5532 3380 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:48:07,640 DEBUG 5532 3380 ocr.py main():41 checking params, error code: 0
2021-04-22 13:48:07,640 DEBUG 5532 3380 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:48:07,640 DEBUG 5532 3380 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:48:07,640 DEBUG 5532 3380 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:48:07,640 INFO 5532 3380 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:48:07,642 INFO 5532 3380 reader.py validate_source():73 scanning files...
2021-04-22 13:48:07,653 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:48:07,654 DEBUG 5532 3380 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:48:08,419 INFO 5532 3380 reader.py output():169 checking output
2021-04-22 13:48:08,419 DEBUG 5532 3380 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:48:08,420 INFO 5532 3380 reader.py merge_output():212 merging scanned output
2021-04-22 13:51:55,428 INFO 7036 1560 ocr.py main():24 Program started
2021-04-22 13:51:55,454 DEBUG 7036 1560 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:51:55,454 DEBUG 7036 1560 ocr.py main():41 checking params, error code: 0
2021-04-22 13:51:55,455 DEBUG 7036 1560 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:51:55,455 DEBUG 7036 1560 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:51:55,455 DEBUG 7036 1560 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:51:55,455 INFO 7036 1560 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:51:55,456 INFO 7036 1560 reader.py validate_source():73 scanning files...
2021-04-22 13:51:55,467 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:51:55,467 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:51:55,467 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:51:55,468 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:51:55,468 DEBUG 7036 1560 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:51:56,211 INFO 7036 1560 reader.py output():169 checking output
2021-04-22 13:51:56,222 DEBUG 7036 1560 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:51:56,222 DEBUG 7036 1560 reader.py output():183 FILE: dest [DND] basename and dest different. dest_file: DND/barbaro.txt
2021-04-22 13:51:56,222 INFO 7036 1560 reader.py merge_output():213 merging scanned output
2021-04-22 13:53:38,363 INFO 7000 5976 ocr.py main():24 Program started
2021-04-22 13:53:38,370 DEBUG 7000 5976 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 13:53:38,370 DEBUG 7000 5976 ocr.py main():41 checking params, error code: 0
2021-04-22 13:53:38,371 DEBUG 7000 5976 reader.py validate_source():46 Files inserted: 1
2021-04-22 13:53:38,371 DEBUG 7000 5976 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 13:53:38,371 DEBUG 7000 5976 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 13:53:38,371 INFO 7000 5976 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 13:53:38,372 INFO 7000 5976 reader.py validate_source():73 scanning files...
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 13:53:38,386 DEBUG 7000 5976 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 13:53:39,288 INFO 7000 5976 reader.py output():169 checking output
2021-04-22 13:53:39,293 DEBUG 7000 5976 reader.py output():177 dirname: DND, path to check = dir
2021-04-22 13:53:39,293 INFO 7000 5976 reader.py create_dir():229 Created directory DND
2021-04-22 13:53:39,310 DEBUG 7000 5976 reader.py validate_dest():246 path dest file: DND/barbaro.txt\scan.txt
2021-04-22 13:53:39,311 DEBUG 7000 5976 reader.py output():191 DIR: dest [DND] exists. dest_file: DND/barbaro.txt\scan.txt
2021-04-22 13:53:39,311 INFO 7000 5976 reader.py merge_output():213 merging scanned output
2021-04-22 13:53:39,311 ERROR 7000 5976 reader.py output():203 Error file not found on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 199, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'DND\\barbaro.txt\\scan.txt'
2021-04-22 14:01:13,819 INFO 3980 4764 ocr.py main():24 Program started
2021-04-22 14:01:13,843 DEBUG 3980 4764 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:01:13,843 DEBUG 3980 4764 ocr.py main():41 checking params, error code: 0
2021-04-22 14:01:13,843 DEBUG 3980 4764 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:01:13,844 DEBUG 3980 4764 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:01:13,844 DEBUG 3980 4764 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:01:13,844 INFO 3980 4764 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:01:13,845 INFO 3980 4764 reader.py validate_source():73 scanning files...
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:01:13,857 DEBUG 3980 4764 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:01:14,616 INFO 3980 4764 reader.py output():169 checking output
2021-04-22 14:01:14,630 DEBUG 3980 4764 reader.py output():180 dirname: DND/classi, path to check = dir
2021-04-22 14:01:14,630 INFO 3980 4764 reader.py create_dir():232 Created directory DND\classi
2021-04-22 14:01:14,647 DEBUG 3980 4764 reader.py validate_dest():249 path dest file: DND/classi/barbaro.txt\scan.txt
2021-04-22 14:01:14,648 DEBUG 3980 4764 reader.py output():194 DIR: dest [DND/classi] exists. dest_file: DND/classi/barbaro.txt\scan.txt
2021-04-22 14:01:14,648 INFO 3980 4764 reader.py merge_output():216 merging scanned output
2021-04-22 14:01:14,680 ERROR 3980 4764 reader.py output():206 Error file not found on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 202, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'DND\\classi\\barbaro.txt\\scan.txt'
2021-04-22 14:01:26,726 INFO 7112 6420 ocr.py main():24 Program started
2021-04-22 14:01:26,747 DEBUG 7112 6420 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:01:26,747 DEBUG 7112 6420 ocr.py main():41 checking params, error code: 0
2021-04-22 14:01:26,747 DEBUG 7112 6420 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:01:26,747 DEBUG 7112 6420 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:01:26,747 DEBUG 7112 6420 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:01:26,748 INFO 7112 6420 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:01:26,748 INFO 7112 6420 reader.py validate_source():73 scanning files...
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:01:26,760 DEBUG 7112 6420 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:01:27,522 INFO 7112 6420 reader.py output():169 checking output
2021-04-22 14:01:27,532 DEBUG 7112 6420 reader.py output():180 dirname: DND/classi, path to check = dir
2021-04-22 14:01:27,533 DEBUG 7112 6420 reader.py output():186 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:01:27,562 INFO 7112 6420 reader.py merge_output():216 merging scanned output
2021-04-22 14:01:27,563 ERROR 7112 6420 reader.py output():204 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 202, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 14:01:56,163 INFO 7096 5524 ocr.py main():24 Program started
2021-04-22 14:01:56,199 DEBUG 7096 5524 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:01:56,199 DEBUG 7096 5524 ocr.py main():41 checking params, error code: 0
2021-04-22 14:01:56,200 DEBUG 7096 5524 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:01:56,200 DEBUG 7096 5524 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:01:56,200 DEBUG 7096 5524 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:01:56,200 INFO 7096 5524 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:01:56,201 INFO 7096 5524 reader.py validate_source():73 scanning files...
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:01:56,214 DEBUG 7096 5524 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:01:57,024 INFO 7096 5524 reader.py output():169 checking output
2021-04-22 14:01:57,031 DEBUG 7096 5524 reader.py output():181 dirname: DND/classi, path to check = dir
2021-04-22 14:01:57,031 DEBUG 7096 5524 reader.py output():187 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:01:57,032 INFO 7096 5524 reader.py merge_output():217 merging scanned output
2021-04-22 14:01:57,032 ERROR 7096 5524 reader.py output():205 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 203, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 14:02:24,914 INFO 6444 6728 ocr.py main():24 Program started
2021-04-22 14:02:24,935 DEBUG 6444 6728 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:02:24,935 DEBUG 6444 6728 ocr.py main():41 checking params, error code: 0
2021-04-22 14:02:24,935 DEBUG 6444 6728 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:02:24,935 DEBUG 6444 6728 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:02:24,935 DEBUG 6444 6728 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:02:24,935 INFO 6444 6728 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:02:24,936 INFO 6444 6728 reader.py validate_source():73 scanning files...
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:02:24,948 DEBUG 6444 6728 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:02:25,694 INFO 6444 6728 reader.py output():169 checking output
2021-04-22 14:02:25,700 DEBUG 6444 6728 reader.py output():181 dirname: DND, path to check = dir
2021-04-22 14:02:25,700 DEBUG 6444 6728 reader.py output():187 FILE: dest [DND] basename and dest different. dest_file: DND/barbaro.txt
2021-04-22 14:02:25,716 INFO 6444 6728 reader.py merge_output():217 merging scanned output
2021-04-22 14:26:54,548 INFO 1676 4292 ocr.py main():24 Program started
2021-04-22 14:26:54,563 DEBUG 1676 4292 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:26:54,563 DEBUG 1676 4292 ocr.py main():41 checking params, error code: 0
2021-04-22 14:26:54,563 DEBUG 1676 4292 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:26:54,563 DEBUG 1676 4292 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:26:54,564 DEBUG 1676 4292 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:26:54,564 INFO 1676 4292 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:26:54,581 INFO 1676 4292 reader.py validate_source():73 scanning files...
2021-04-22 14:26:54,593 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:26:54,594 DEBUG 1676 4292 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:26:55,346 INFO 1676 4292 reader.py output():169 checking output
2021-04-22 14:26:55,361 DEBUG 1676 4292 reader.py output():181 dirname: DND, path to check = dir
2021-04-22 14:26:55,361 DEBUG 1676 4292 reader.py output():187 FILE: dest [DND] basename and dest different. dest_file: DND/barbaro.txt
2021-04-22 14:26:55,375 INFO 1676 4292 reader.py merge_output():217 merging scanned output
2021-04-22 14:28:39,895 INFO 4728 2128 ocr.py main():24 Program started
2021-04-22 14:28:39,919 DEBUG 4728 2128 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:28:39,919 DEBUG 4728 2128 ocr.py main():41 checking params, error code: 0
2021-04-22 14:28:39,919 DEBUG 4728 2128 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:28:39,920 DEBUG 4728 2128 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:28:39,920 DEBUG 4728 2128 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:28:39,920 INFO 4728 2128 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:28:39,921 INFO 4728 2128 reader.py validate_source():73 scanning files...
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:28:39,932 DEBUG 4728 2128 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:28:40,688 INFO 4728 2128 reader.py output():169 checking output
2021-04-22 14:28:40,695 DEBUG 4728 2128 reader.py output():181 dirname: DND/classi, path to check = dir
2021-04-22 14:28:40,695 DEBUG 4728 2128 reader.py output():187 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/barbaro.txt
2021-04-22 14:28:40,696 INFO 4728 2128 reader.py merge_output():217 merging scanned output
2021-04-22 14:29:27,407 INFO 5816 2256 ocr.py main():24 Program started
2021-04-22 14:29:27,430 DEBUG 5816 2256 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:29:27,430 DEBUG 5816 2256 ocr.py main():41 checking params, error code: 0
2021-04-22 14:29:27,430 DEBUG 5816 2256 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:29:27,431 DEBUG 5816 2256 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:29:27,431 DEBUG 5816 2256 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:29:27,431 INFO 5816 2256 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:29:27,431 INFO 5816 2256 reader.py validate_source():73 scanning files...
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:29:27,474 DEBUG 5816 2256 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:29:28,203 INFO 5816 2256 reader.py output():169 checking output
2021-04-22 14:29:28,204 DEBUG 5816 2256 reader.py output():181 dirname: DND/classi, path to check = dir
2021-04-22 14:29:28,205 DEBUG 5816 2256 reader.py output():187 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:29:28,219 INFO 5816 2256 reader.py merge_output():217 merging scanned output
2021-04-22 14:29:28,220 ERROR 5816 2256 reader.py output():205 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 203, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 14:36:26,001 INFO 908 6332 ocr.py main():24 Program started
2021-04-22 14:36:26,023 DEBUG 908 6332 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 14:36:26,023 DEBUG 908 6332 ocr.py main():41 checking params, error code: 0
2021-04-22 14:36:26,023 DEBUG 908 6332 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:36:26,024 DEBUG 908 6332 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:36:26,024 DEBUG 908 6332 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:36:26,024 INFO 908 6332 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:36:26,025 INFO 908 6332 reader.py validate_source():73 scanning files...
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:36:26,037 DEBUG 908 6332 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:36:26,783 INFO 908 6332 reader.py output():169 checking output
2021-04-22 14:36:26,812 DEBUG 908 6332 reader.py output():182 dirname: DND/classi, path to check = dir
2021-04-22 14:36:26,812 DEBUG 908 6332 reader.py output():188 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/barbaro.txt
2021-04-22 14:36:26,827 INFO 908 6332 reader.py merge_output():218 merging scanned output
2021-04-22 14:36:55,309 INFO 4292 6796 ocr.py main():24 Program started
2021-04-22 14:36:55,326 DEBUG 4292 6796 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=DND/classi/, lang=eng, prefix=scan, stats=False
2021-04-22 14:36:55,326 DEBUG 4292 6796 ocr.py main():41 checking params, error code: 0
2021-04-22 14:36:55,326 DEBUG 4292 6796 reader.py validate_source():46 Files inserted: 1
2021-04-22 14:36:55,327 DEBUG 4292 6796 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 14:36:55,327 DEBUG 4292 6796 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 14:36:55,327 INFO 4292 6796 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 14:36:55,328 INFO 4292 6796 reader.py validate_source():73 scanning files...
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 14:36:55,340 DEBUG 4292 6796 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 14:36:56,102 INFO 4292 6796 reader.py output():169 checking output
2021-04-22 14:36:56,104 DEBUG 4292 6796 reader.py output():182 dirname: DND/classi, path to check = dir
2021-04-22 14:36:56,104 DEBUG 4292 6796 reader.py output():188 FILE: dest [DND/classi] basename and dest different. dest_file: DND/classi/
2021-04-22 14:36:56,104 INFO 4292 6796 reader.py merge_output():218 merging scanned output
2021-04-22 14:36:56,105 ERROR 4292 6796 reader.py output():206 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 204, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'DND\\classi'
2021-04-22 15:04:23,039 INFO 5904 5836 ocr.py main():24 Program started
2021-04-22 15:04:23,046 DEBUG 5904 5836 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/scan.txt, lang=eng, prefix=scan, stats=False
2021-04-22 15:04:23,046 DEBUG 5904 5836 ocr.py main():41 checking params, error code: 0
2021-04-22 15:04:23,046 DEBUG 5904 5836 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:04:23,047 DEBUG 5904 5836 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:04:23,047 DEBUG 5904 5836 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:04:23,047 INFO 5904 5836 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:04:23,063 INFO 5904 5836 reader.py validate_source():73 scanning files...
2021-04-22 15:04:23,108 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:04:23,109 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:04:23,109 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:04:23,109 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:04:23,110 DEBUG 5904 5836 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:04:23,857 INFO 5904 5836 reader.py output():169 checking output
2021-04-22 15:04:23,876 DEBUG 5904 5836 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:04:23,876 DEBUG 5904 5836 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/scan.txt
2021-04-22 15:04:23,876 INFO 5904 5836 reader.py merge_output():219 merging scanned output
2021-04-22 15:05:42,916 INFO 5620 4968 ocr.py main():24 Program started
2021-04-22 15:05:42,944 DEBUG 5620 4968 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/scan.txt, lang=eng, prefix=scan, stats=False
2021-04-22 15:05:42,944 DEBUG 5620 4968 ocr.py main():41 checking params, error code: 0
2021-04-22 15:05:42,944 DEBUG 5620 4968 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:05:42,944 DEBUG 5620 4968 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:05:42,946 DEBUG 5620 4968 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:05:42,946 INFO 5620 4968 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:05:42,946 INFO 5620 4968 reader.py validate_source():73 scanning files...
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:05:42,959 DEBUG 5620 4968 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:05:43,711 INFO 5620 4968 reader.py output():169 checking output
2021-04-22 15:05:43,728 DEBUG 5620 4968 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:05:43,728 DEBUG 5620 4968 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/scan.txt
2021-04-22 15:05:43,728 INFO 5620 4968 reader.py merge_output():219 merging scanned output
2021-04-22 15:06:50,648 INFO 6696 5396 ocr.py main():24 Program started
2021-04-22 15:06:50,669 DEBUG 6696 5396 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/, lang=eng, prefix=scan, stats=False
2021-04-22 15:06:50,670 DEBUG 6696 5396 ocr.py main():41 checking params, error code: 0
2021-04-22 15:06:50,670 DEBUG 6696 5396 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:06:50,670 DEBUG 6696 5396 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:06:50,671 DEBUG 6696 5396 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:06:50,671 INFO 6696 5396 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:06:50,671 INFO 6696 5396 reader.py validate_source():73 scanning files...
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:06:50,684 DEBUG 6696 5396 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:06:51,429 INFO 6696 5396 reader.py output():169 checking output
2021-04-22 15:06:51,456 DEBUG 6696 5396 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:06:51,456 DEBUG 6696 5396 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/
2021-04-22 15:06:51,456 INFO 6696 5396 reader.py merge_output():219 merging scanned output
2021-04-22 15:06:51,457 ERROR 6696 5396 reader.py output():207 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'scans'
2021-04-22 15:10:55,133 INFO 2088 3796 ocr.py main():24 Program started
2021-04-22 15:10:55,161 DEBUG 2088 3796 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans, lang=eng, prefix=scan, stats=False
2021-04-22 15:10:55,161 DEBUG 2088 3796 ocr.py main():41 checking params, error code: 0
2021-04-22 15:10:55,161 DEBUG 2088 3796 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:10:55,161 DEBUG 2088 3796 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:10:55,161 DEBUG 2088 3796 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:10:55,161 INFO 2088 3796 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:10:55,161 INFO 2088 3796 reader.py validate_source():73 scanning files...
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:10:55,175 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:10:55,176 DEBUG 2088 3796 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:10:56,024 INFO 2088 3796 reader.py output():169 checking output
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py validate_dest():252 path dest file: scans\scan.txt
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py validate_dest():256 dir content: ['scan.txt']
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py validate_dest():266 dest file: scans\scan_1.txt
2021-04-22 15:10:56,046 DEBUG 2088 3796 reader.py output():191 DIR: dest [scans] exists. dest_file: scans\scan_1.txt
2021-04-22 15:10:56,047 INFO 2088 3796 reader.py merge_output():219 merging scanned output
2021-04-22 15:12:48,341 INFO 6296 4304 ocr.py main():24 Program started
2021-04-22 15:12:48,359 DEBUG 6296 4304 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane, lang=eng, prefix=scan, stats=False
2021-04-22 15:12:48,359 DEBUG 6296 4304 ocr.py main():41 checking params, error code: 0
2021-04-22 15:12:48,359 DEBUG 6296 4304 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:12:48,359 DEBUG 6296 4304 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:12:48,359 DEBUG 6296 4304 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:12:48,359 INFO 6296 4304 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:12:48,360 INFO 6296 4304 reader.py validate_source():73 scanning files...
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:12:48,373 DEBUG 6296 4304 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:12:49,133 INFO 6296 4304 reader.py output():169 checking output
2021-04-22 15:12:49,160 DEBUG 6296 4304 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:12:49,160 DEBUG 6296 4304 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/cane
2021-04-22 15:12:49,160 INFO 6296 4304 reader.py merge_output():219 merging scanned output
2021-04-22 15:12:53,117 INFO 6008 1560 ocr.py main():24 Program started
2021-04-22 15:12:53,139 DEBUG 6008 1560 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane/, lang=eng, prefix=scan, stats=False
2021-04-22 15:12:53,139 DEBUG 6008 1560 ocr.py main():41 checking params, error code: 0
2021-04-22 15:12:53,139 DEBUG 6008 1560 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:12:53,140 DEBUG 6008 1560 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:12:53,140 DEBUG 6008 1560 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:12:53,140 INFO 6008 1560 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:12:53,141 INFO 6008 1560 reader.py validate_source():73 scanning files...
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:12:53,153 DEBUG 6008 1560 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:12:53,914 INFO 6008 1560 reader.py output():169 checking output
2021-04-22 15:12:53,934 DEBUG 6008 1560 reader.py output():182 dirname: scans/cane, path to check = dir
2021-04-22 15:12:53,935 DEBUG 6008 1560 reader.py output():201 FILE: dest [scans/cane] exists. dest_file: scans/cane/
2021-04-22 15:12:53,935 INFO 6008 1560 reader.py merge_output():219 merging scanned output
2021-04-22 15:13:18,327 INFO 5232 2792 ocr.py main():24 Program started
2021-04-22 15:13:18,355 DEBUG 5232 2792 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane, lang=eng, prefix=scan, stats=False
2021-04-22 15:13:18,355 DEBUG 5232 2792 ocr.py main():41 checking params, error code: 0
2021-04-22 15:13:18,355 DEBUG 5232 2792 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:13:18,356 DEBUG 5232 2792 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:13:18,356 DEBUG 5232 2792 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:13:18,356 INFO 5232 2792 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:13:18,357 INFO 5232 2792 reader.py validate_source():73 scanning files...
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:13:18,370 DEBUG 5232 2792 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:13:19,117 INFO 5232 2792 reader.py output():169 checking output
2021-04-22 15:13:19,142 DEBUG 5232 2792 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:13:19,142 DEBUG 5232 2792 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/cane
2021-04-22 15:13:19,143 INFO 5232 2792 reader.py merge_output():219 merging scanned output
2021-04-22 15:13:30,898 INFO 1868 2628 ocr.py main():24 Program started
2021-04-22 15:13:30,923 DEBUG 1868 2628 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=scans/cane, lang=eng, prefix=scan, stats=False
2021-04-22 15:13:30,923 DEBUG 1868 2628 ocr.py main():41 checking params, error code: 0
2021-04-22 15:13:30,923 DEBUG 1868 2628 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:13:30,923 DEBUG 1868 2628 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:13:30,924 DEBUG 1868 2628 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:13:30,924 INFO 1868 2628 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:13:30,924 INFO 1868 2628 reader.py validate_source():73 scanning files...
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:13:30,937 DEBUG 1868 2628 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:13:31,711 INFO 1868 2628 reader.py output():169 checking output
2021-04-22 15:13:31,739 DEBUG 1868 2628 reader.py output():182 dirname: scans, path to check = dir
2021-04-22 15:13:31,739 DEBUG 1868 2628 reader.py output():188 FILE: dest [scans] basename and dest different. dest_file: scans/cane
2021-04-22 15:13:31,739 INFO 1868 2628 reader.py merge_output():219 merging scanned output
2021-04-22 15:36:54,656 INFO 5508 3412 ocr.py main():24 Program started
2021-04-22 15:36:54,676 DEBUG 5508 3412 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd, lang=eng, prefix=scan, stats=False
2021-04-22 15:36:54,676 DEBUG 5508 3412 ocr.py main():41 checking params, error code: 0
2021-04-22 15:36:54,676 DEBUG 5508 3412 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:36:54,676 DEBUG 5508 3412 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:36:54,677 DEBUG 5508 3412 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:36:54,677 INFO 5508 3412 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:36:54,677 INFO 5508 3412 reader.py validate_source():73 scanning files...
2021-04-22 15:36:54,690 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:36:54,691 DEBUG 5508 3412 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:36:55,455 INFO 5508 3412 reader.py output():169 checking output
2021-04-22 15:36:55,472 DEBUG 5508 3412 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:36:55,473 INFO 5508 3412 reader.py create_dir():235 Created directory dnd
2021-04-22 15:36:55,474 DEBUG 5508 3412 reader.py output():196 DIR: dest [dnd] exists. dest_file: dnd
2021-04-22 15:36:55,474 INFO 5508 3412 reader.py merge_output():219 merging scanned output
2021-04-22 15:36:55,475 ERROR 5508 3412 reader.py output():207 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'dnd'
2021-04-22 15:37:14,141 INFO 5148 6888 ocr.py main():24 Program started
2021-04-22 15:37:14,170 DEBUG 5148 6888 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-22 15:37:14,170 DEBUG 5148 6888 ocr.py main():41 checking params, error code: 0
2021-04-22 15:37:14,170 DEBUG 5148 6888 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:37:14,170 DEBUG 5148 6888 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:37:14,170 DEBUG 5148 6888 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:37:14,171 INFO 5148 6888 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:37:14,171 INFO 5148 6888 reader.py validate_source():73 scanning files...
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:37:14,183 DEBUG 5148 6888 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:37:14,937 INFO 5148 6888 reader.py output():169 checking output
2021-04-22 15:37:14,959 DEBUG 5148 6888 reader.py output():182 dirname: dnd, path to check = dir
2021-04-22 15:37:14,959 INFO 5148 6888 reader.py create_dir():235 Created directory dnd
2021-04-22 15:37:14,960 DEBUG 5148 6888 reader.py output():196 DIR: dest [dnd] exists. dest_file: dnd/barbaro.txt
2021-04-22 15:37:14,960 INFO 5148 6888 reader.py merge_output():219 merging scanned output
2021-04-22 15:37:24,438 INFO 5800 4748 ocr.py main():24 Program started
2021-04-22 15:37:24,444 DEBUG 5800 4748 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd, lang=eng, prefix=scan, stats=False
2021-04-22 15:37:24,444 DEBUG 5800 4748 ocr.py main():41 checking params, error code: 0
2021-04-22 15:37:24,444 DEBUG 5800 4748 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:37:24,444 DEBUG 5800 4748 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:37:24,444 DEBUG 5800 4748 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:37:24,444 INFO 5800 4748 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:37:24,459 INFO 5800 4748 reader.py validate_source():73 scanning files...
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:37:24,472 DEBUG 5800 4748 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:37:25,220 INFO 5800 4748 reader.py output():169 checking output
2021-04-22 15:37:25,245 DEBUG 5800 4748 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:37:25,246 DEBUG 5800 4748 reader.py validate_dest():252 path dest file: dnd\scan.txt
2021-04-22 15:37:25,246 DEBUG 5800 4748 reader.py output():191 DIR: dest [dnd] exists. dest_file: dnd\scan.txt
2021-04-22 15:37:25,248 INFO 5800 4748 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:08,828 INFO 4332 6948 ocr.py main():24 Program started
2021-04-22 15:39:08,856 DEBUG 4332 6948 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi/baba.tzt, lang=eng, prefix=scan, stats=False
2021-04-22 15:39:08,857 DEBUG 4332 6948 ocr.py main():41 checking params, error code: 0
2021-04-22 15:39:08,857 DEBUG 4332 6948 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:39:08,857 DEBUG 4332 6948 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:39:08,857 DEBUG 4332 6948 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:39:08,858 INFO 4332 6948 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:39:08,860 INFO 4332 6948 reader.py validate_source():73 scanning files...
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:39:08,872 DEBUG 4332 6948 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:39:09,611 INFO 4332 6948 reader.py output():169 checking output
2021-04-22 15:39:09,634 DEBUG 4332 6948 reader.py output():182 dirname: dnd/classi, path to check = dir
2021-04-22 15:39:09,634 INFO 4332 6948 reader.py create_dir():235 Created directory dnd\classi
2021-04-22 15:39:09,635 DEBUG 4332 6948 reader.py output():196 DIR: dest [dnd/classi] exists. dest_file: dnd/classi/baba.tzt
2021-04-22 15:39:09,636 INFO 4332 6948 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:41,012 INFO 6828 3980 ocr.py main():24 Program started
2021-04-22 15:39:41,042 DEBUG 6828 3980 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=baba.tzt, lang=eng, prefix=scan, stats=False
2021-04-22 15:39:41,043 DEBUG 6828 3980 ocr.py main():41 checking params, error code: 0
2021-04-22 15:39:41,043 DEBUG 6828 3980 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:39:41,043 DEBUG 6828 3980 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:39:41,043 DEBUG 6828 3980 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:39:41,044 INFO 6828 3980 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:39:41,044 INFO 6828 3980 reader.py validate_source():73 scanning files...
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:39:41,057 DEBUG 6828 3980 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:39:41,814 INFO 6828 3980 reader.py output():169 checking output
2021-04-22 15:39:41,834 DEBUG 6828 3980 reader.py output():179 dirname empty. path to check = dest
2021-04-22 15:39:41,834 DEBUG 6828 3980 reader.py output():201 FILE: dest [baba.tzt] exists. dest_file: baba.tzt
2021-04-22 15:39:41,834 INFO 6828 3980 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:46,454 INFO 6952 4884 ocr.py main():24 Program started
2021-04-22 15:39:46,480 DEBUG 6952 4884 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=baba/, lang=eng, prefix=scan, stats=False
2021-04-22 15:39:46,480 DEBUG 6952 4884 ocr.py main():41 checking params, error code: 0
2021-04-22 15:39:46,480 DEBUG 6952 4884 reader.py validate_source():46 Files inserted: 1
2021-04-22 15:39:46,480 DEBUG 6952 4884 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-22 15:39:46,480 DEBUG 6952 4884 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-22 15:39:46,480 INFO 6952 4884 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-22 15:39:46,481 INFO 6952 4884 reader.py validate_source():73 scanning files...
2021-04-22 15:39:46,493 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-22 15:39:46,493 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-22 15:39:46,494 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-22 15:39:46,494 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-22 15:39:46,494 DEBUG 6952 4884 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-22 15:39:47,235 INFO 6952 4884 reader.py output():169 checking output
2021-04-22 15:39:47,260 DEBUG 6952 4884 reader.py output():182 dirname: baba, path to check = dir
2021-04-22 15:39:47,260 INFO 6952 4884 reader.py create_dir():235 Created directory baba
2021-04-22 15:39:47,260 DEBUG 6952 4884 reader.py output():196 DIR: dest [baba] exists. dest_file: baba/
2021-04-22 15:39:47,261 INFO 6952 4884 reader.py merge_output():219 merging scanned output
2021-04-22 15:39:47,261 ERROR 6952 4884 reader.py output():207 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'baba'
2021-04-29 08:33:06,778 INFO 5892 2180 ocr.py main():24 Program started
2021-04-29 08:33:06,811 DEBUG 5892 2180 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-29 08:33:06,811 DEBUG 5892 2180 ocr.py main():41 checking params, error code: 0
2021-04-29 08:33:06,811 DEBUG 5892 2180 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:33:06,812 DEBUG 5892 2180 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:33:06,812 DEBUG 5892 2180 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:33:06,812 INFO 5892 2180 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:33:06,813 INFO 5892 2180 reader.py validate_source():73 scanning files...
2021-04-29 08:33:06,862 DEBUG 5892 2180 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:33:06,864 DEBUG 5892 2180 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:33:06,864 DEBUG 5892 2180 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:33:06,864 DEBUG 5892 2180 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:33:06,864 DEBUG 5892 2180 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:33:07,607 INFO 5892 2180 reader.py output():169 checking output
2021-04-29 08:33:07,640 DEBUG 5892 2180 reader.py output():182 dirname: dnd/classi, path to check = dir
2021-04-29 08:33:07,644 ERROR 5892 2180 reader.py create_dir():237 Directory dnd\classi already exists
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 234, in create_dir
    os.mkdir(path)
FileNotFoundError: [WinError 3] Impossibile trovare il percorso specificato: 'dnd\\classi'
2021-04-29 08:33:07,646 DEBUG 5892 2180 reader.py output():196 DIR: dest [dnd/classi] exists. dest_file: dnd/classi/barbaro.txt
2021-04-29 08:33:07,647 INFO 5892 2180 reader.py merge_output():219 merging scanned output
2021-04-29 08:33:07,647 ERROR 5892 2180 reader.py output():209 Error file not found on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dnd\\classi\\barbaro.txt'
2021-04-29 08:34:05,028 INFO 4732 2680 ocr.py main():24 Program started
2021-04-29 08:34:05,058 DEBUG 4732 2680 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-29 08:34:05,058 DEBUG 4732 2680 ocr.py main():41 checking params, error code: 0
2021-04-29 08:34:05,058 DEBUG 4732 2680 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:34:05,058 DEBUG 4732 2680 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:34:05,059 DEBUG 4732 2680 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:34:05,059 INFO 4732 2680 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:34:05,061 INFO 4732 2680 reader.py validate_source():73 scanning files...
2021-04-29 08:34:05,073 DEBUG 4732 2680 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:34:05,074 DEBUG 4732 2680 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:34:05,074 DEBUG 4732 2680 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:34:05,074 DEBUG 4732 2680 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:34:05,074 DEBUG 4732 2680 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:34:05,857 INFO 4732 2680 reader.py output():169 checking output
2021-04-29 08:34:05,891 DEBUG 4732 2680 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:34:05,892 INFO 4732 2680 reader.py create_dir():235 Created directory dnd
2021-04-29 08:34:05,893 DEBUG 4732 2680 reader.py output():196 DIR: dest [dnd] exists. dest_file: dnd/barbaro.txt
2021-04-29 08:34:05,893 INFO 4732 2680 reader.py merge_output():219 merging scanned output
2021-04-29 08:36:11,013 INFO 6068 6940 ocr.py main():24 Program started
2021-04-29 08:36:11,034 DEBUG 6068 6940 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=classi, lang=eng, prefix=scan, stats=False
2021-04-29 08:36:11,034 DEBUG 6068 6940 ocr.py main():41 checking params, error code: 0
2021-04-29 08:36:11,034 DEBUG 6068 6940 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:36:11,034 DEBUG 6068 6940 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:36:11,034 DEBUG 6068 6940 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:36:11,034 INFO 6068 6940 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:36:11,034 INFO 6068 6940 reader.py validate_source():73 scanning files...
2021-04-29 08:36:11,047 DEBUG 6068 6940 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:36:11,047 DEBUG 6068 6940 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:36:11,047 DEBUG 6068 6940 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:36:11,047 DEBUG 6068 6940 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:36:11,048 DEBUG 6068 6940 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:36:11,763 INFO 6068 6940 reader.py output():169 checking output
2021-04-29 08:36:11,795 DEBUG 6068 6940 reader.py output():179 dirname empty. path to check = dest
2021-04-29 08:36:11,796 INFO 6068 6940 reader.py create_dir():235 Created directory classi
2021-04-29 08:36:11,796 DEBUG 6068 6940 reader.py output():196 DIR: dest [classi] exists. dest_file: classi
2021-04-29 08:36:11,797 INFO 6068 6940 reader.py merge_output():219 merging scanned output
2021-04-29 08:36:11,797 ERROR 6068 6940 reader.py output():207 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 205, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'classi'
2021-04-29 08:39:58,972 INFO 4564 5788 ocr.py main():24 Program started
2021-04-29 08:39:58,978 DEBUG 4564 5788 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=classi, lang=eng, prefix=scan, stats=False
2021-04-29 08:39:58,978 DEBUG 4564 5788 ocr.py main():41 checking params, error code: 0
2021-04-29 08:39:58,978 DEBUG 4564 5788 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:39:58,978 DEBUG 4564 5788 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:39:58,978 DEBUG 4564 5788 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:39:58,979 INFO 4564 5788 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:39:58,979 INFO 4564 5788 reader.py validate_source():73 scanning files...
2021-04-29 08:39:58,991 DEBUG 4564 5788 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:39:58,991 DEBUG 4564 5788 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:39:58,991 DEBUG 4564 5788 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:39:58,991 DEBUG 4564 5788 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:39:58,991 DEBUG 4564 5788 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:39:59,778 INFO 4564 5788 reader.py output():169 checking output
2021-04-29 08:39:59,803 DEBUG 4564 5788 reader.py output():179 dirname empty. path to check = dest
2021-04-29 08:39:59,804 DEBUG 4564 5788 reader.py validate_dest():255 path dest file: classi\scan.txt
2021-04-29 08:39:59,804 DEBUG 4564 5788 reader.py output():191 DIR: dest [classi] exists. dest_file: classi\scan.txt
2021-04-29 08:39:59,804 INFO 4564 5788 reader.py merge_output():222 merging scanned output
2021-04-29 08:40:58,700 INFO 3616 5764 ocr.py main():24 Program started
2021-04-29 08:40:58,729 DEBUG 3616 5764 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 08:40:58,729 DEBUG 3616 5764 ocr.py main():41 checking params, error code: 0
2021-04-29 08:40:58,729 DEBUG 3616 5764 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:40:58,730 DEBUG 3616 5764 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:40:58,730 DEBUG 3616 5764 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:40:58,730 INFO 3616 5764 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:40:58,732 INFO 3616 5764 reader.py validate_source():73 scanning files...
2021-04-29 08:40:58,744 DEBUG 3616 5764 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:40:58,744 DEBUG 3616 5764 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:40:58,745 DEBUG 3616 5764 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:40:58,745 DEBUG 3616 5764 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:40:58,745 DEBUG 3616 5764 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:40:59,614 INFO 3616 5764 reader.py output():169 checking output
2021-04-29 08:40:59,617 DEBUG 3616 5764 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:40:59,617 INFO 3616 5764 reader.py create_dir():238 Created directory dnd
2021-04-29 08:40:59,618 DEBUG 3616 5764 reader.py validate_dest():255 path dest file: dnd\scan.txt
2021-04-29 08:40:59,618 DEBUG 3616 5764 reader.py output():199 DIR: dest [dnd] exists. dest_file: dnd\scan.txt
2021-04-29 08:40:59,619 INFO 3616 5764 reader.py merge_output():222 merging scanned output
2021-04-29 08:44:26,372 INFO 4560 2932 ocr.py main():24 Program started
2021-04-29 08:44:26,401 DEBUG 4560 2932 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/barbaro.txt, lang=eng, prefix=scan, stats=False
2021-04-29 08:44:26,401 DEBUG 4560 2932 ocr.py main():41 checking params, error code: 0
2021-04-29 08:44:26,401 DEBUG 4560 2932 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:44:26,402 DEBUG 4560 2932 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:44:26,402 DEBUG 4560 2932 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:44:26,402 INFO 4560 2932 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:44:26,404 INFO 4560 2932 reader.py validate_source():73 scanning files...
2021-04-29 08:44:26,421 DEBUG 4560 2932 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:44:26,421 DEBUG 4560 2932 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:44:26,421 DEBUG 4560 2932 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:44:26,421 DEBUG 4560 2932 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:44:26,422 DEBUG 4560 2932 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:44:27,154 INFO 4560 2932 reader.py output():169 checking output
2021-04-29 08:44:27,177 DEBUG 4560 2932 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:44:27,178 INFO 4560 2932 reader.py create_dir():238 Created directory dnd
2021-04-29 08:44:27,179 DEBUG 4560 2932 reader.py validate_dest():255 path dest file: dnd\scan.txt
2021-04-29 08:44:27,179 DEBUG 4560 2932 reader.py output():199 DIR: dest [dnd] exists. dest_file: dnd\scan.txt
2021-04-29 08:44:27,179 INFO 4560 2932 reader.py merge_output():222 merging scanned output
2021-04-29 08:44:42,045 INFO 1916 4672 ocr.py main():24 Program started
2021-04-29 08:44:42,072 DEBUG 1916 4672 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 08:44:42,072 DEBUG 1916 4672 ocr.py main():41 checking params, error code: 0
2021-04-29 08:44:42,072 DEBUG 1916 4672 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:44:42,073 DEBUG 1916 4672 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:44:42,073 DEBUG 1916 4672 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:44:42,073 INFO 1916 4672 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:44:42,074 INFO 1916 4672 reader.py validate_source():73 scanning files...
2021-04-29 08:44:42,086 DEBUG 1916 4672 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:44:42,086 DEBUG 1916 4672 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:44:42,086 DEBUG 1916 4672 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:44:42,086 DEBUG 1916 4672 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:44:42,087 DEBUG 1916 4672 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:44:42,829 INFO 1916 4672 reader.py output():169 checking output
2021-04-29 08:44:42,831 DEBUG 1916 4672 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:44:42,832 DEBUG 1916 4672 reader.py output():188 FILE: dest [dnd] basename and dest different. dest_file: dnd/
2021-04-29 08:44:42,833 INFO 1916 4672 reader.py merge_output():222 merging scanned output
2021-04-29 08:44:42,834 ERROR 1916 4672 reader.py output():210 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 208, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'dnd'
2021-04-29 08:46:33,115 INFO 1972 3416 ocr.py main():24 Program started
2021-04-29 08:46:33,152 DEBUG 1972 3416 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 08:46:33,152 DEBUG 1972 3416 ocr.py main():41 checking params, error code: 0
2021-04-29 08:46:33,152 DEBUG 1972 3416 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:46:33,152 DEBUG 1972 3416 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:46:33,152 DEBUG 1972 3416 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:46:33,152 INFO 1972 3416 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:46:33,154 INFO 1972 3416 reader.py validate_source():73 scanning files...
2021-04-29 08:46:33,166 DEBUG 1972 3416 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:46:33,166 DEBUG 1972 3416 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:46:33,166 DEBUG 1972 3416 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:46:33,166 DEBUG 1972 3416 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:46:33,166 DEBUG 1972 3416 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:46:34,075 INFO 1972 3416 reader.py output():169 checking output
2021-04-29 08:46:34,102 DEBUG 1972 3416 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:46:34,102 DEBUG 1972 3416 reader.py output():188 FILE: dest [dnd] basename and dest different. dest_file: dnd/
2021-04-29 08:46:34,103 INFO 1972 3416 reader.py merge_output():222 merging scanned output
2021-04-29 08:46:34,104 ERROR 1972 3416 reader.py output():210 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 208, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'dnd'
2021-04-29 08:47:17,690 INFO 2460 2452 ocr.py main():24 Program started
2021-04-29 08:47:17,727 DEBUG 2460 2452 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 08:47:17,727 DEBUG 2460 2452 ocr.py main():41 checking params, error code: 0
2021-04-29 08:47:17,727 DEBUG 2460 2452 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:47:17,727 DEBUG 2460 2452 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:47:17,728 DEBUG 2460 2452 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:47:17,728 INFO 2460 2452 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:47:17,729 INFO 2460 2452 reader.py validate_source():73 scanning files...
2021-04-29 08:47:17,752 DEBUG 2460 2452 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:47:17,752 DEBUG 2460 2452 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:47:17,752 DEBUG 2460 2452 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:47:17,752 DEBUG 2460 2452 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:47:17,752 DEBUG 2460 2452 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:47:18,528 INFO 2460 2452 reader.py output():169 checking output
2021-04-29 08:47:18,550 DEBUG 2460 2452 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:47:18,550 DEBUG 2460 2452 reader.py output():188 FILE: dest [dnd] basename and dest different. dest_file: dnd/
2021-04-29 08:47:18,550 INFO 2460 2452 reader.py merge_output():223 merging scanned output
2021-04-29 08:47:18,551 ERROR 2460 2452 reader.py output():211 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 209, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 153, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'dnd'
2021-04-29 08:48:35,497 INFO 2452 1748 ocr.py main():24 Program started
2021-04-29 08:48:35,528 DEBUG 2452 1748 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd, lang=eng, prefix=scan, stats=False
2021-04-29 08:48:35,528 DEBUG 2452 1748 ocr.py main():41 checking params, error code: 0
2021-04-29 08:48:35,529 DEBUG 2452 1748 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:48:35,529 DEBUG 2452 1748 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:48:35,529 DEBUG 2452 1748 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:48:35,529 INFO 2452 1748 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:48:35,530 INFO 2452 1748 reader.py validate_source():73 scanning files...
2021-04-29 08:48:35,542 DEBUG 2452 1748 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:48:35,543 DEBUG 2452 1748 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:48:35,543 DEBUG 2452 1748 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:48:35,543 DEBUG 2452 1748 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:48:35,543 DEBUG 2452 1748 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:48:36,294 INFO 2452 1748 reader.py output():169 checking output
2021-04-29 08:48:36,344 DEBUG 2452 1748 reader.py output():179 dirname empty. path to check = dest
2021-04-29 08:48:36,345 DEBUG 2452 1748 reader.py validate_dest():255 path dest file: dnd\scan.txt
2021-04-29 08:48:36,345 DEBUG 2452 1748 reader.py validate_dest():259 dir content: ['scan.txt']
2021-04-29 08:48:36,345 DEBUG 2452 1748 reader.py validate_dest():269 dest file: dnd\scan_1.txt
2021-04-29 08:48:36,345 DEBUG 2452 1748 reader.py output():191 DIR: dest [dnd] exists. dest_file: dnd\scan_1.txt
2021-04-29 08:48:36,346 INFO 2452 1748 reader.py merge_output():222 merging scanned output
2021-04-29 08:49:39,575 INFO 1708 5540 ocr.py main():24 Program started
2021-04-29 08:49:39,602 DEBUG 1708 5540 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi, lang=eng, prefix=scan, stats=False
2021-04-29 08:49:39,602 DEBUG 1708 5540 ocr.py main():41 checking params, error code: 0
2021-04-29 08:49:39,603 DEBUG 1708 5540 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:49:39,603 DEBUG 1708 5540 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:49:39,603 DEBUG 1708 5540 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:49:39,603 INFO 1708 5540 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:49:39,604 INFO 1708 5540 reader.py validate_source():73 scanning files...
2021-04-29 08:49:39,616 DEBUG 1708 5540 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:49:39,616 DEBUG 1708 5540 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:49:39,616 DEBUG 1708 5540 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:49:39,617 DEBUG 1708 5540 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:49:39,617 DEBUG 1708 5540 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:49:40,341 INFO 1708 5540 reader.py output():169 checking output
2021-04-29 08:49:40,364 DEBUG 1708 5540 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:49:40,364 DEBUG 1708 5540 reader.py output():188 FILE: dest [dnd] basename and dest different. dest_file: dnd/classi
2021-04-29 08:49:40,365 INFO 1708 5540 reader.py merge_output():222 merging scanned output
2021-04-29 08:51:39,044 INFO 5672 3932 ocr.py main():24 Program started
2021-04-29 08:51:39,071 DEBUG 5672 3932 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi, lang=eng, prefix=scan, stats=False
2021-04-29 08:51:39,071 DEBUG 5672 3932 ocr.py main():41 checking params, error code: 0
2021-04-29 08:51:39,071 DEBUG 5672 3932 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:51:39,072 DEBUG 5672 3932 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:51:39,072 DEBUG 5672 3932 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:51:39,072 INFO 5672 3932 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:51:39,073 INFO 5672 3932 reader.py validate_source():73 scanning files...
2021-04-29 08:51:39,084 DEBUG 5672 3932 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:51:39,084 DEBUG 5672 3932 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:51:39,084 DEBUG 5672 3932 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:51:39,085 DEBUG 5672 3932 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:51:39,085 DEBUG 5672 3932 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:51:39,825 INFO 5672 3932 reader.py output():169 checking output
2021-04-29 08:51:39,871 DEBUG 5672 3932 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:51:39,871 DEBUG 5672 3932 reader.py validate_dest():256 path dest file: dnd\scan.txt
2021-04-29 08:51:39,875 DEBUG 5672 3932 reader.py validate_dest():260 dir content: ['scan.txt', 'scan_1.txt']
2021-04-29 08:51:39,875 DEBUG 5672 3932 reader.py validate_dest():270 dest file: dnd\scan_2.txt
2021-04-29 08:51:39,875 DEBUG 5672 3932 reader.py output():189 FILE: dest [dnd] basename and dest different. dest_file: dnd\scan_2.txt
2021-04-29 08:51:39,876 INFO 5672 3932 reader.py merge_output():223 merging scanned output
2021-04-29 08:53:14,591 INFO 3524 4536 ocr.py main():24 Program started
2021-04-29 08:53:14,599 DEBUG 3524 4536 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi, lang=eng, prefix=scan, stats=False
2021-04-29 08:53:14,600 DEBUG 3524 4536 ocr.py main():41 checking params, error code: 0
2021-04-29 08:53:14,600 DEBUG 3524 4536 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:53:14,600 DEBUG 3524 4536 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:53:14,600 DEBUG 3524 4536 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:53:14,600 INFO 3524 4536 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:53:14,601 INFO 3524 4536 reader.py validate_source():73 scanning files...
2021-04-29 08:53:14,613 DEBUG 3524 4536 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:53:14,613 DEBUG 3524 4536 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:53:14,613 DEBUG 3524 4536 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:53:14,613 DEBUG 3524 4536 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:53:14,613 DEBUG 3524 4536 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:53:15,573 INFO 3524 4536 reader.py output():169 checking output
2021-04-29 08:53:15,611 DEBUG 3524 4536 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:53:15,611 INFO 3524 4536 reader.py create_dir():238 Created directory dnd
2021-04-29 08:53:15,612 DEBUG 3524 4536 reader.py validate_dest():255 path dest file: dnd\scan.txt
2021-04-29 08:53:15,612 DEBUG 3524 4536 reader.py output():199 DIR: dest [dnd] exists. dest_file: dnd\scan.txt
2021-04-29 08:53:15,612 INFO 3524 4536 reader.py merge_output():222 merging scanned output
2021-04-29 08:53:29,935 INFO 5692 4844 ocr.py main():24 Program started
2021-04-29 08:53:29,961 DEBUG 5692 4844 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi, lang=eng, prefix=scan, stats=False
2021-04-29 08:53:29,961 DEBUG 5692 4844 ocr.py main():41 checking params, error code: 0
2021-04-29 08:53:29,961 DEBUG 5692 4844 reader.py validate_source():46 Files inserted: 1
2021-04-29 08:53:29,961 DEBUG 5692 4844 reader.py validate_source():54 Source after mask: ['img/barbaro.png']
2021-04-29 08:53:29,961 DEBUG 5692 4844 reader.py has_valid_ext():89 File img/barbaro.png is valid
2021-04-29 08:53:29,961 INFO 5692 4844 reader.py validate_source():72 List of valid files (1): ['img/barbaro.png']
2021-04-29 08:53:29,962 INFO 5692 4844 reader.py validate_source():73 scanning files...
2021-04-29 08:53:30,002 DEBUG 5692 4844 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 08:53:30,002 DEBUG 5692 4844 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 08:53:30,003 DEBUG 5692 4844 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 08:53:30,003 DEBUG 5692 4844 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 08:53:30,003 DEBUG 5692 4844 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 08:53:30,716 INFO 5692 4844 reader.py output():169 checking output
2021-04-29 08:53:30,743 DEBUG 5692 4844 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 08:53:30,744 DEBUG 5692 4844 reader.py output():188 FILE: dest [dnd] basename and dest different. dest_file: dnd/classi.txt
2021-04-29 08:53:30,744 INFO 5692 4844 reader.py merge_output():222 merging scanned output
2021-04-29 09:28:47,278 INFO 4488 6268 ocr.py main():24 Program started
2021-04-29 09:28:47,308 DEBUG 4488 6268 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi.txt, lang=eng, prefix=scan, stats=False
2021-04-29 09:28:47,309 DEBUG 4488 6268 ocr.py main():41 checking params, error code: 0
2021-04-29 09:29:08,482 INFO 3508 1912 ocr.py main():24 Program started
2021-04-29 09:29:08,521 DEBUG 3508 1912 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/classi.txt, lang=eng, prefix=scan, stats=False
2021-04-29 09:29:08,522 DEBUG 3508 1912 ocr.py main():41 checking params, error code: 0
2021-04-29 09:29:08,522 DEBUG 3508 1912 reader.py validate_source():48 Files inserted: 1
2021-04-29 09:29:08,523 DEBUG 3508 1912 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 09:29:08,524 DEBUG 3508 1912 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 09:29:08,524 INFO 3508 1912 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 09:29:08,524 INFO 3508 1912 reader.py validate_source():75 scanning files...
2021-04-29 09:29:08,537 DEBUG 3508 1912 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 09:29:08,599 DEBUG 3508 1912 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 09:29:08,599 DEBUG 3508 1912 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 09:29:08,600 DEBUG 3508 1912 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 09:29:08,600 DEBUG 3508 1912 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 09:29:09,435 INFO 3508 1912 reader.py output():171 checking output
2021-04-29 09:29:09,435 DEBUG 3508 1912 reader.py output():175 basename: classi.txt, ext ('dnd/classi', '.txt'), dirname: dnd
2021-04-29 09:29:09,435 DEBUG 3508 1912 reader.py output():182 dirname: dnd, path to check = dir
2021-04-29 09:29:09,436 INFO 3508 1912 reader.py create_dir():241 Created directory dnd
2021-04-29 09:29:09,454 DEBUG 3508 1912 reader.py validate_dest():258 path dest file: dnd\scan.txt
2021-04-29 09:29:09,455 DEBUG 3508 1912 reader.py output():201 DIR: dest [dnd] exists. dest_file: dnd\scan.txt
2021-04-29 09:29:09,456 DEBUG 3508 1912 reader.py output():208 dest file: dnd\scan.txt
2021-04-29 09:29:09,456 INFO 3508 1912 reader.py merge_output():225 merging scanned output
2021-04-29 09:34:15,856 INFO 3816 700 ocr.py main():24 Program started
2021-04-29 09:34:15,863 DEBUG 3816 700 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd, lang=eng, prefix=scan, stats=False
2021-04-29 09:34:15,863 DEBUG 3816 700 ocr.py main():41 checking params, error code: 0
2021-04-29 09:34:15,863 DEBUG 3816 700 reader.py validate_source():48 Files inserted: 1
2021-04-29 09:34:15,864 DEBUG 3816 700 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 09:34:15,864 DEBUG 3816 700 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 09:34:15,865 INFO 3816 700 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 09:34:15,865 INFO 3816 700 reader.py validate_source():75 scanning files...
2021-04-29 09:34:15,877 DEBUG 3816 700 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 09:34:15,896 DEBUG 3816 700 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 09:34:15,896 DEBUG 3816 700 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 09:34:15,896 DEBUG 3816 700 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 09:34:15,897 DEBUG 3816 700 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 09:34:16,622 INFO 3816 700 reader.py output():171 checking output
2021-04-29 09:34:16,626 DEBUG 3816 700 reader.py output():176 basename: dnd, ext ('dnd', ''), dirname: 
2021-04-29 09:34:16,626 DEBUG 3816 700 reader.py output():180 dirname empty. path to check = dest
2021-04-29 09:34:16,626 DEBUG 3816 700 reader.py validate_dest():259 path dest file: dnd\scan.txt
2021-04-29 09:34:16,644 DEBUG 3816 700 reader.py validate_dest():263 dir content: ['scan.txt']
2021-04-29 09:34:16,645 DEBUG 3816 700 reader.py validate_dest():273 dest file: dnd\scan_1.txt
2021-04-29 09:34:16,645 DEBUG 3816 700 reader.py output():194 DIR: dest [dnd] exists. dest_file: dnd\scan_1.txt
2021-04-29 09:34:16,645 DEBUG 3816 700 reader.py output():209 dest file: dnd\scan_1.txt
2021-04-29 09:34:16,646 INFO 3816 700 reader.py merge_output():226 merging scanned output
2021-04-29 09:36:07,637 INFO 1912 96 ocr.py main():24 Program started
2021-04-29 09:36:07,662 DEBUG 1912 96 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/dnd.txt, lang=eng, prefix=scan, stats=False
2021-04-29 09:36:07,662 DEBUG 1912 96 ocr.py main():41 checking params, error code: 0
2021-04-29 09:36:07,663 DEBUG 1912 96 reader.py validate_source():48 Files inserted: 1
2021-04-29 09:36:07,663 DEBUG 1912 96 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 09:36:07,664 DEBUG 1912 96 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 09:36:07,664 INFO 1912 96 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 09:36:07,665 INFO 1912 96 reader.py validate_source():75 scanning files...
2021-04-29 09:36:07,677 DEBUG 1912 96 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 09:36:07,696 DEBUG 1912 96 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 09:36:07,697 DEBUG 1912 96 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 09:36:07,697 DEBUG 1912 96 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 09:36:07,698 DEBUG 1912 96 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 09:36:08,435 INFO 1912 96 reader.py output():171 checking output
2021-04-29 09:36:08,449 DEBUG 1912 96 reader.py output():176 basename: dnd.txt, ext ('dnd/dnd', '.txt'), dirname: dnd
2021-04-29 09:36:08,449 DEBUG 1912 96 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 09:36:08,449 DEBUG 1912 96 reader.py output():191 FILE: dest [dnd] basename and dest different. dest_file: dnd/dnd.txt.txt
2021-04-29 09:36:08,469 DEBUG 1912 96 reader.py output():209 dest file: dnd/dnd.txt.txt
2021-04-29 09:36:08,469 INFO 1912 96 reader.py merge_output():226 merging scanned output
2021-04-29 09:41:37,153 INFO 6656 5944 ocr.py main():24 Program started
2021-04-29 09:41:37,188 DEBUG 6656 5944 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 09:41:37,188 DEBUG 6656 5944 ocr.py main():41 checking params, error code: 0
2021-04-29 09:41:37,188 DEBUG 6656 5944 reader.py validate_source():48 Files inserted: 1
2021-04-29 09:41:37,188 DEBUG 6656 5944 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 09:41:37,189 DEBUG 6656 5944 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 09:41:37,189 INFO 6656 5944 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 09:41:37,190 INFO 6656 5944 reader.py validate_source():75 scanning files...
2021-04-29 09:41:37,202 DEBUG 6656 5944 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 09:41:37,260 DEBUG 6656 5944 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 09:41:37,260 DEBUG 6656 5944 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 09:41:37,260 DEBUG 6656 5944 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 09:41:37,261 DEBUG 6656 5944 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 09:41:38,013 INFO 6656 5944 reader.py output():171 checking output
2021-04-29 09:41:38,014 DEBUG 6656 5944 reader.py output():176 basename: , ext ('dnd/', ''), dirname: dnd
2021-04-29 09:41:38,014 DEBUG 6656 5944 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 09:41:38,014 DEBUG 6656 5944 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/.txt
2021-04-29 09:41:38,033 DEBUG 6656 5944 reader.py output():211 dest file: dnd/.txt
2021-04-29 09:41:38,034 INFO 6656 5944 reader.py merge_output():228 merging scanned output
2021-04-29 10:11:56,603 INFO 104 6352 ocr.py main():24 Program started
2021-04-29 10:11:56,634 DEBUG 104 6352 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 10:11:56,635 DEBUG 104 6352 ocr.py main():41 checking params, error code: 0
2021-04-29 10:11:56,635 DEBUG 104 6352 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:11:56,636 DEBUG 104 6352 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:11:56,661 DEBUG 104 6352 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:11:56,693 INFO 104 6352 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:11:56,694 INFO 104 6352 reader.py validate_source():75 scanning files...
2021-04-29 10:11:56,723 DEBUG 104 6352 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:11:56,729 DEBUG 104 6352 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:11:56,730 DEBUG 104 6352 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:11:56,731 DEBUG 104 6352 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:11:56,791 DEBUG 104 6352 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:11:57,528 INFO 104 6352 reader.py output():171 checking output
2021-04-29 10:11:57,530 DEBUG 104 6352 reader.py output():176 basename: , ext ('dnd/', ''), dirname: dnd
2021-04-29 10:11:57,530 DEBUG 104 6352 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 10:11:57,530 DEBUG 104 6352 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/.txt
2021-04-29 10:11:57,549 DEBUG 104 6352 reader.py output():211 dest file: dnd/.txt
2021-04-29 10:11:57,550 INFO 104 6352 reader.py merge_output():228 merging scanned output
2021-04-29 10:12:07,528 INFO 5552 5824 ocr.py main():24 Program started
2021-04-29 10:12:07,553 DEBUG 5552 5824 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 10:12:07,553 DEBUG 5552 5824 ocr.py main():41 checking params, error code: 0
2021-04-29 10:12:07,554 DEBUG 5552 5824 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:12:07,554 DEBUG 5552 5824 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:12:07,555 DEBUG 5552 5824 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:12:07,555 INFO 5552 5824 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:12:07,556 INFO 5552 5824 reader.py validate_source():75 scanning files...
2021-04-29 10:12:07,568 DEBUG 5552 5824 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:12:07,639 DEBUG 5552 5824 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:12:07,639 DEBUG 5552 5824 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:12:07,640 DEBUG 5552 5824 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:12:07,641 DEBUG 5552 5824 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:12:08,372 INFO 5552 5824 reader.py output():171 checking output
2021-04-29 10:12:08,378 DEBUG 5552 5824 reader.py output():176 basename: , ext ('dnd/', ''), dirname: dnd
2021-04-29 10:12:08,378 DEBUG 5552 5824 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 10:12:08,378 DEBUG 5552 5824 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/.txt
2021-04-29 10:12:08,397 DEBUG 5552 5824 reader.py output():211 dest file: dnd/.txt
2021-04-29 10:12:08,397 INFO 5552 5824 reader.py merge_output():228 merging scanned output
2021-04-29 10:12:39,854 INFO 7084 2196 ocr.py main():24 Program started
2021-04-29 10:12:39,892 DEBUG 7084 2196 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 10:12:39,893 DEBUG 7084 2196 ocr.py main():41 checking params, error code: 0
2021-04-29 10:12:39,893 DEBUG 7084 2196 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:12:39,894 DEBUG 7084 2196 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:12:39,894 DEBUG 7084 2196 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:12:39,895 INFO 7084 2196 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:12:39,895 INFO 7084 2196 reader.py validate_source():75 scanning files...
2021-04-29 10:12:39,908 DEBUG 7084 2196 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:12:39,969 DEBUG 7084 2196 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:12:39,969 DEBUG 7084 2196 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:12:39,970 DEBUG 7084 2196 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:12:39,970 DEBUG 7084 2196 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:12:40,759 INFO 7084 2196 reader.py output():171 checking output
2021-04-29 10:12:40,771 DEBUG 7084 2196 reader.py output():176 basename: , ext ('dnd/', ''), dirname: dnd
2021-04-29 10:12:40,777 DEBUG 7084 2196 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 10:12:40,835 DEBUG 7084 2196 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/.txt
2021-04-29 10:12:40,869 DEBUG 7084 2196 reader.py output():211 dest file: dnd/.txt
2021-04-29 10:12:40,871 INFO 7084 2196 reader.py merge_output():228 merging scanned output
2021-04-29 10:13:09,345 INFO 4172 6568 ocr.py main():24 Program started
2021-04-29 10:13:09,350 DEBUG 4172 6568 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/, lang=eng, prefix=scan, stats=False
2021-04-29 10:13:09,351 DEBUG 4172 6568 ocr.py main():41 checking params, error code: 0
2021-04-29 10:13:09,351 DEBUG 4172 6568 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:13:09,351 DEBUG 4172 6568 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:13:09,352 DEBUG 4172 6568 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:13:09,352 INFO 4172 6568 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:13:09,353 INFO 4172 6568 reader.py validate_source():75 scanning files...
2021-04-29 10:13:09,391 DEBUG 4172 6568 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:13:09,412 DEBUG 4172 6568 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:13:09,416 DEBUG 4172 6568 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:13:09,417 DEBUG 4172 6568 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:13:09,417 DEBUG 4172 6568 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:13:10,289 INFO 4172 6568 reader.py output():171 checking output
2021-04-29 10:13:10,290 DEBUG 4172 6568 reader.py output():176 basename: , ext ('dnd/', ''), dirname: dnd
2021-04-29 10:13:10,290 DEBUG 4172 6568 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 10:13:10,291 DEBUG 4172 6568 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/
2021-04-29 10:13:10,327 DEBUG 4172 6568 reader.py output():211 dest file: dnd/
2021-04-29 10:13:10,327 INFO 4172 6568 reader.py merge_output():228 merging scanned output
2021-04-29 10:13:10,328 ERROR 4172 6568 reader.py output():215 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 213, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 155, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'dnd'
2021-04-29 10:13:18,170 INFO 6824 1180 ocr.py main():24 Program started
2021-04-29 10:13:18,182 DEBUG 6824 1180 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=.\scans, lang=eng, prefix=scan, stats=False
2021-04-29 10:13:18,182 DEBUG 6824 1180 ocr.py main():41 checking params, error code: 0
2021-04-29 10:13:18,183 DEBUG 6824 1180 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:13:18,183 DEBUG 6824 1180 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:13:18,184 DEBUG 6824 1180 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:13:18,184 INFO 6824 1180 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:13:18,184 INFO 6824 1180 reader.py validate_source():75 scanning files...
2021-04-29 10:13:18,254 DEBUG 6824 1180 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:13:18,255 DEBUG 6824 1180 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:13:18,255 DEBUG 6824 1180 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:13:18,256 DEBUG 6824 1180 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:13:18,256 DEBUG 6824 1180 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:13:18,998 INFO 6824 1180 reader.py output():171 checking output
2021-04-29 10:13:19,005 DEBUG 6824 1180 reader.py output():176 basename: scans, ext ('.\\scans', ''), dirname: .
2021-04-29 10:13:19,005 DEBUG 6824 1180 reader.py output():180 dirname empty. path to check = dest
2021-04-29 10:13:19,008 INFO 6824 1180 reader.py create_dir():244 Created directory scans
2021-04-29 10:13:19,027 DEBUG 6824 1180 reader.py output():204 DIR: dest [.\scans] exists. dest_file: .\scans
2021-04-29 10:13:19,028 DEBUG 6824 1180 reader.py output():211 dest file: .\scans
2021-04-29 10:13:19,029 INFO 6824 1180 reader.py merge_output():228 merging scanned output
2021-04-29 10:13:19,029 ERROR 6824 1180 reader.py output():215 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 213, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 155, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'scans'
2021-04-29 10:13:29,528 INFO 7076 216 ocr.py main():24 Program started
2021-04-29 10:13:29,553 DEBUG 7076 216 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=.\scans, lang=eng, prefix=scan, stats=False
2021-04-29 10:13:29,554 DEBUG 7076 216 ocr.py main():41 checking params, error code: 0
2021-04-29 10:13:29,554 DEBUG 7076 216 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:13:29,554 DEBUG 7076 216 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:13:29,555 DEBUG 7076 216 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:13:29,555 INFO 7076 216 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:13:29,556 INFO 7076 216 reader.py validate_source():75 scanning files...
2021-04-29 10:13:29,587 DEBUG 7076 216 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:13:29,588 DEBUG 7076 216 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:13:29,588 DEBUG 7076 216 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:13:29,589 DEBUG 7076 216 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:13:29,589 DEBUG 7076 216 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:13:30,356 INFO 7076 216 reader.py output():171 checking output
2021-04-29 10:13:30,357 DEBUG 7076 216 reader.py output():176 basename: scans, ext ('.\\scans', ''), dirname: .
2021-04-29 10:13:30,358 DEBUG 7076 216 reader.py output():180 dirname empty. path to check = dest
2021-04-29 10:13:30,358 DEBUG 7076 216 reader.py output():193 FILE: dest [.\scans] basename and dest different. dest_file: .\scans
2021-04-29 10:13:30,359 DEBUG 7076 216 reader.py output():211 dest file: .\scans
2021-04-29 10:13:30,359 INFO 7076 216 reader.py merge_output():228 merging scanned output
2021-04-29 10:13:30,360 ERROR 7076 216 reader.py output():215 Permission error on <module 'ntpath' from 'C:\\Python39\\lib\\ntpath.py'>
Traceback (most recent call last):
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 213, in output
    write_output(merge_output(output), dest_file)
  File "C:\Users\admin\Documents\ocr_cli\src\ocr_scripts\reader.py", line 155, in write_output
    with open(path, "w", encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'scans'
2021-04-29 10:13:40,529 INFO 4624 3792 ocr.py main():24 Program started
2021-04-29 10:13:40,557 DEBUG 4624 3792 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/intro.txt, lang=eng, prefix=scan, stats=False
2021-04-29 10:13:40,558 DEBUG 4624 3792 ocr.py main():41 checking params, error code: 0
2021-04-29 10:13:40,558 DEBUG 4624 3792 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:13:40,559 DEBUG 4624 3792 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:13:40,560 DEBUG 4624 3792 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:13:40,560 INFO 4624 3792 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:13:40,561 INFO 4624 3792 reader.py validate_source():75 scanning files...
2021-04-29 10:13:40,573 DEBUG 4624 3792 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:13:40,573 DEBUG 4624 3792 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:13:40,574 DEBUG 4624 3792 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:13:40,574 DEBUG 4624 3792 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:13:40,594 DEBUG 4624 3792 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:13:41,309 INFO 4624 3792 reader.py output():171 checking output
2021-04-29 10:13:41,320 DEBUG 4624 3792 reader.py output():176 basename: intro.txt, ext ('dnd/intro', '.txt'), dirname: dnd
2021-04-29 10:13:41,320 DEBUG 4624 3792 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 10:13:41,320 DEBUG 4624 3792 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/intro.txt
2021-04-29 10:13:41,339 DEBUG 4624 3792 reader.py output():211 dest file: dnd/intro.txt
2021-04-29 10:13:41,339 INFO 4624 3792 reader.py merge_output():228 merging scanned output
2021-04-29 10:13:50,134 INFO 5912 1600 ocr.py main():24 Program started
2021-04-29 10:13:54,669 INFO 272 276 ocr.py main():24 Program started
2021-04-29 10:13:54,693 DEBUG 272 276 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/intro.txt, lang=eng, prefix=scan, stats=True
2021-04-29 10:13:54,693 DEBUG 272 276 ocr.py main():41 checking params, error code: 0
2021-04-29 10:13:54,693 DEBUG 272 276 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:13:54,694 DEBUG 272 276 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:13:54,695 DEBUG 272 276 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:13:54,695 INFO 272 276 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:13:54,696 INFO 272 276 reader.py validate_source():75 scanning files...
2021-04-29 10:13:54,708 DEBUG 272 276 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:13:54,766 DEBUG 272 276 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:13:54,768 DEBUG 272 276 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:13:54,769 DEBUG 272 276 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:13:54,769 DEBUG 272 276 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:13:55,498 INFO 272 276 reader.py output():171 checking output
2021-04-29 10:13:55,504 DEBUG 272 276 reader.py output():176 basename: intro.txt, ext ('dnd/intro', '.txt'), dirname: dnd
2021-04-29 10:13:55,504 DEBUG 272 276 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 10:13:55,505 DEBUG 272 276 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/intro.txt
2021-04-29 10:13:55,523 DEBUG 272 276 reader.py output():211 dest file: dnd/intro.txt
2021-04-29 10:13:55,523 INFO 272 276 reader.py merge_output():228 merging scanned output
2021-04-29 10:13:55,524 INFO 272 276 stats.py count_words():29 parole contate: 217
2021-04-29 10:14:40,516 INFO 1680 2268 ocr.py main():24 Program started
2021-04-29 10:14:40,520 DEBUG 1680 2268 ocr.py main():36 parametri creati: source=['img/barbaro.png'], dest=dnd/intro.txt, lang=eng, prefix=scan, stats=True
2021-04-29 10:14:40,520 DEBUG 1680 2268 ocr.py main():41 checking params, error code: 0
2021-04-29 10:14:40,520 DEBUG 1680 2268 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:14:40,521 DEBUG 1680 2268 reader.py validate_source():56 Source after mask: ['img/barbaro.png']
2021-04-29 10:14:40,521 DEBUG 1680 2268 reader.py has_valid_ext():91 File img/barbaro.png is valid
2021-04-29 10:14:40,522 INFO 1680 2268 reader.py validate_source():74 List of valid files (1): ['img/barbaro.png']
2021-04-29 10:14:40,522 INFO 1680 2268 reader.py validate_source():75 scanning files...
2021-04-29 10:14:40,535 DEBUG 1680 2268 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:14:40,594 DEBUG 1680 2268 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:14:40,594 DEBUG 1680 2268 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:14:40,594 DEBUG 1680 2268 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:14:40,595 DEBUG 1680 2268 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:14:41,407 INFO 1680 2268 reader.py output():171 checking output
2021-04-29 10:14:41,408 DEBUG 1680 2268 reader.py output():176 basename: intro.txt, ext ('dnd/intro', '.txt'), dirname: dnd
2021-04-29 10:14:41,408 DEBUG 1680 2268 reader.py output():183 dirname: dnd, path to check = dir
2021-04-29 10:14:41,409 DEBUG 1680 2268 reader.py output():193 FILE: dest [dnd] basename and dest different. dest_file: dnd/intro.txt
2021-04-29 10:14:41,409 DEBUG 1680 2268 reader.py output():211 dest file: dnd/intro.txt
2021-04-29 10:14:41,410 INFO 1680 2268 reader.py merge_output():228 merging scanned output
2021-04-29 10:14:41,411 INFO 1680 2268 stats.py count_words():29 parole contate: 217
2021-04-29 10:15:09,747 INFO 6404 6644 ocr.py main():24 Program started
2021-04-29 10:15:09,770 DEBUG 6404 6644 ocr.py main():36 parametri creati: source=['img/*.png'], dest=scans/full.txt, lang=eng, prefix=scan, stats=True
2021-04-29 10:15:09,771 DEBUG 6404 6644 ocr.py main():41 checking params, error code: 0
2021-04-29 10:15:09,771 DEBUG 6404 6644 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:15:09,772 DEBUG 6404 6644 reader.py validate_source():56 Source after mask: ['img\\barbaro.PNG', 'img\\introDnd.PNG', 'img\\engtxtpng.png', 'img\\itatxtpng.png']
2021-04-29 10:15:09,773 DEBUG 6404 6644 reader.py has_valid_ext():91 File img\barbaro.PNG is valid
2021-04-29 10:15:09,773 DEBUG 6404 6644 reader.py has_valid_ext():91 File img\introDnd.PNG is valid
2021-04-29 10:15:09,774 DEBUG 6404 6644 reader.py has_valid_ext():91 File img\engtxtpng.png is valid
2021-04-29 10:15:09,774 DEBUG 6404 6644 reader.py has_valid_ext():91 File img\itatxtpng.png is valid
2021-04-29 10:15:09,775 INFO 6404 6644 reader.py validate_source():74 List of valid files (4): ['img\\barbaro.PNG', 'img\\introDnd.PNG', 'img\\engtxtpng.png', 'img\\itatxtpng.png']
2021-04-29 10:15:09,775 INFO 6404 6644 reader.py validate_source():75 scanning files...
2021-04-29 10:15:09,787 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:15:09,805 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:15:09,806 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:15:09,806 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:15:09,807 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:15:10,575 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:15:10,587 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:15:10,605 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:15:10,605 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:15:10,612 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:15:11,200 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:15:11,210 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:15:11,210 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:15:11,210 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'PLTE' 70 768
2021-04-29 10:15:11,228 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'pHYs' 850 9
2021-04-29 10:15:11,228 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IDAT' 871 32520
2021-04-29 10:15:11,778 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:15:11,792 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:15:11,792 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:15:11,792 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:15:11,809 DEBUG 6404 6644 PngImagePlugin.py call():186 STREAM b'IDAT' 91 34093
2021-04-29 10:15:12,403 INFO 6404 6644 reader.py output():171 checking output
2021-04-29 10:15:12,407 DEBUG 6404 6644 reader.py output():176 basename: full.txt, ext ('scans/full', '.txt'), dirname: scans
2021-04-29 10:15:12,407 DEBUG 6404 6644 reader.py output():183 dirname: scans, path to check = dir
2021-04-29 10:15:12,407 DEBUG 6404 6644 reader.py output():193 FILE: dest [scans] basename and dest different. dest_file: scans/full.txt
2021-04-29 10:15:12,425 DEBUG 6404 6644 reader.py output():211 dest file: scans/full.txt
2021-04-29 10:15:12,426 INFO 6404 6644 reader.py merge_output():228 merging scanned output
2021-04-29 10:19:05,432 INFO 3112 6084 ocr.py main():24 Program started
2021-04-29 10:19:05,466 DEBUG 3112 6084 ocr.py main():36 parametri creati: source=['img/*.png'], dest=scans/full.txt, lang=eng, prefix=scan, stats=True
2021-04-29 10:19:05,467 DEBUG 3112 6084 ocr.py main():41 checking params, error code: 0
2021-04-29 10:19:05,467 DEBUG 3112 6084 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:19:05,469 DEBUG 3112 6084 reader.py validate_source():56 Source after mask: ['img\\barbaro.PNG', 'img\\introDnd.PNG', 'img\\engtxtpng.png', 'img\\itatxtpng.png']
2021-04-29 10:19:05,470 DEBUG 3112 6084 reader.py has_valid_ext():91 File img\barbaro.PNG is valid
2021-04-29 10:19:05,471 DEBUG 3112 6084 reader.py has_valid_ext():91 File img\introDnd.PNG is valid
2021-04-29 10:19:05,471 DEBUG 3112 6084 reader.py has_valid_ext():91 File img\engtxtpng.png is valid
2021-04-29 10:19:05,472 DEBUG 3112 6084 reader.py has_valid_ext():91 File img\itatxtpng.png is valid
2021-04-29 10:19:05,473 INFO 3112 6084 reader.py validate_source():74 List of valid files (4): ['img\\barbaro.PNG', 'img\\introDnd.PNG', 'img\\engtxtpng.png', 'img\\itatxtpng.png']
2021-04-29 10:19:05,473 INFO 3112 6084 reader.py validate_source():75 scanning files...
2021-04-29 10:19:05,507 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:19:05,508 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:19:05,508 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:19:05,508 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:19:05,509 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:19:06,271 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:19:06,271 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:19:06,272 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:19:06,272 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:19:06,307 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IDAT' 91 65445
2021-04-29 10:19:06,872 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:19:06,879 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:19:06,879 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:19:06,879 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'PLTE' 70 768
2021-04-29 10:19:06,897 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'pHYs' 850 9
2021-04-29 10:19:06,898 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IDAT' 871 32520
2021-04-29 10:19:07,529 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IHDR' 16 13
2021-04-29 10:19:07,544 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'sRGB' 41 1
2021-04-29 10:19:07,544 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'gAMA' 54 4
2021-04-29 10:19:07,544 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'pHYs' 70 9
2021-04-29 10:19:07,565 DEBUG 3112 6084 PngImagePlugin.py call():186 STREAM b'IDAT' 91 34093
2021-04-29 10:19:08,278 INFO 3112 6084 reader.py output():171 checking output
2021-04-29 10:19:08,298 DEBUG 3112 6084 reader.py output():176 basename: full.txt, ext ('scans/full', '.txt'), dirname: scans
2021-04-29 10:19:08,298 DEBUG 3112 6084 reader.py output():183 dirname: scans, path to check = dir
2021-04-29 10:19:08,315 DEBUG 3112 6084 reader.py output():193 FILE: dest [scans] basename and dest different. dest_file: scans/full.txt
2021-04-29 10:19:08,317 DEBUG 3112 6084 reader.py output():211 dest file: scans/full.txt
2021-04-29 10:19:08,317 INFO 3112 6084 reader.py merge_output():228 merging scanned output
2021-04-29 10:19:08,318 INFO 3112 6084 stats.py count_words():29 parole contate: 504
2021-04-29 10:19:40,560 INFO 268 4380 ocr.py main():24 Program started
2021-04-29 10:19:40,594 DEBUG 268 4380 ocr.py main():36 parametri creati: source=['img/*.jpg'], dest=scans/full.txt, lang=eng, prefix=scan, stats=True
2021-04-29 10:19:40,594 DEBUG 268 4380 ocr.py main():41 checking params, error code: 0
2021-04-29 10:19:40,595 DEBUG 268 4380 reader.py validate_source():48 Files inserted: 1
2021-04-29 10:19:40,596 DEBUG 268 4380 reader.py validate_source():56 Source after mask: ['img\\engtxtjpg.jpg', 'img\\itatxtjpg.jpg']
2021-04-29 10:19:40,597 DEBUG 268 4380 reader.py has_valid_ext():91 File img\engtxtjpg.jpg is valid
2021-04-29 10:19:40,598 DEBUG 268 4380 reader.py has_valid_ext():91 File img\itatxtjpg.jpg is valid
2021-04-29 10:19:40,598 INFO 268 4380 reader.py validate_source():74 List of valid files (2): ['img\\engtxtjpg.jpg', 'img\\itatxtjpg.jpg']
2021-04-29 10:19:40,598 INFO 268 4380 reader.py validate_source():75 scanning files...
2021-04-29 10:19:43,653 INFO 268 4380 reader.py output():171 checking output
2021-04-29 10:19:43,665 DEBUG 268 4380 reader.py output():176 basename: full.txt, ext ('scans/full', '.txt'), dirname: scans
2021-04-29 10:19:43,665 DEBUG 268 4380 reader.py output():183 dirname: scans, path to check = dir
2021-04-29 10:19:43,666 DEBUG 268 4380 reader.py output():193 FILE: dest [scans] basename and dest different. dest_file: scans/full.txt
2021-04-29 10:19:43,686 DEBUG 268 4380 reader.py output():211 dest file: scans/full.txt
2021-04-29 10:19:43,686 INFO 268 4380 reader.py merge_output():228 merging scanned output
2021-04-29 10:19:43,691 INFO 268 4380 stats.py count_words():29 parole contate: 647
